1. PSX_GET_PENDING_BATCH_ID

create or replace PROCEDURE PSX_GET_PENDING_BATCH_ID(
    p_batch_id OUT VARCHAR2,  -- Output parameter for batch_id
    p_status OUT VARCHAR2     -- Output parameter for status ('C' for success, 'E' for error)
)AS
        PSXBATCHID VARCHAR2(50);
        p_batch_id_Account  VARCHAR2(50);
        -- ENQUE MESSAGE VARIABLES --
    agent sys.aq$_agent := sys.aq$_agent(' ', NULL, 0);
    MESSAGE sys.aq$_jms_message;
    enqueue_options dbms_aq.enqueue_options_t;
    message_properties dbms_aq.message_properties_t;
    msgid raw(16);
    json_payload       VARCHAR2(4000); -- JSON payload

BEGIN

    BEGIN
        -- Getting the BATCH_ID
        SELECT /*+ enable_parallel_dml parallel(6) */ BATCH_ID
        INTO p_batch_id
        FROM PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T
        WHERE SL = (SELECT /*+ enable_parallel_dml parallel(6) */ MIN(sl) FROM PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T WHERE EOD_STATUS = 'P' AND DATA_CATEGORY='CUSTOMER')
        AND EOD_STATUS = 'P' AND DATA_CATEGORY='CUSTOMER';
Commit;

        -- Returning "C" in case of success
        p_status := 'C';        
    EXCEPTION
        -- Handling no data found error
         -- Handling no data found error
        WHEN NO_DATA_FOUND THEN
            p_batch_id := NULL;
            p_status := 'E';  -- Return 'E' for error

        -- Handle any other exception
        SELECT /*+ enable_parallel_dml parallel(6) */ BATCH_ID
        INTO p_batch_id_Account
        FROM PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T
        WHERE SL = (SELECT /*+ enable_parallel_dml parallel(6) */ MIN(sl) FROM PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T WHERE EOD_STATUS = 'P' AND DATA_CATEGORY='ACCOUNTS')
        AND EOD_STATUS = 'P' AND DATA_CATEGORY='ACCOUNTS';
Commit;
        -- GENERATE PSX_BATCH_ID IF CUSTOMER DATA = 0 --------
        PSXBATCHID := TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS');
        UPDATE PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T SET PSX_BATCH_ID = PSXBATCHID WHERE BATCH_ID = p_batch_id_Account AND DATA_CATEGORY='ACCOUNTS';


         -- Enqueue PSX_EOD_QUEUE
        MESSAGE := sys.aq$_jms_message.construct(dbms_aq.JMS_TEXT_MESSAGE);
        message.set_replyto(agent);
        message.set_type('tkaqpet2');
        message.set_userid('yesbnk');
        message.set_appid('plsql_enq');
        message.set_groupid('st');
        message.set_groupseq(1);
        message.set_Short_Property('systemId',1);
        message.set_Long_Property('psxIdBatchId',PSXBATCHID);  -- Use the input batch ID
        message.set_Short_Property('purposeId',99);
        message.set_string_property('PSX_BATCH_ID', PSXBATCHID); 
        message.set_text(json_payload);

    DBMS_AQ.ENQUEUE(
        queue_name => 'PROD_PRIME360DEDUPE.PSX_EOD_QUEUE',
        enqueue_options => enqueue_options,
        message_properties => message_properties,
        payload => message,
        msgid => msgid
    );
    COMMIT;

        WHEN OTHERS THEN
            p_batch_id := NULL;
            p_status := 'E';  -- Return 'E' for error
--            p_descripition := 'Error in the PSX_GET_PENDING_BATCH_ID PROCEDURE';
--            p_sqlerror := 'Error: ' || SQLERRM || ' at ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;
            RAISE_APPLICATION_ERROR(-20001, 'Error occurred in the PSX_GET_PENDING_BATCH_ID procedure: ' || SQLERRM);

             -- Update the EOD_STATUS in the target schema based on the provided batch IDs
    UPDATE PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T
    SET EOD_STATUS = 'E'
    WHERE BATCH_ID = p_batch_id
    AND DATA_CATEGORY='CUSTOMER';
    END;
END PSX_GET_PENDING_BATCH_ID;
==================================================================================================================

2. PSX_VALIDATE_COUNTS

create or replace PROCEDURE PSX_VALIDATE_COUNTS(v_psx_batch_id IN VARCHAR2,v_batch_id IN VARCHAR2, o_status OUT VARCHAR2,o_descripition OUT VARCHAR2, o_sqlerror OUT VARCHAR2) AS
    input_batchid_cnt_in_ybl_t NUMBER;
    control_table_count NUMBER;
    incremental_table_distinct_count NUMBER;
    actual_count NUMBER;
    eod_status_u_src_sys_count NUMBER;
    sum_batch_total_rec_count NUMBER;
    batchid_not_found EXCEPTION;      -- Exception for input batch_id not found in YBL_CUSTOMER_DATA_INCREMENTAL
    invalid_source_system EXCEPTION;  -- Exception for invalid source systems
    count_mismatch EXCEPTION;         -- Exception for data count count mismatches
    no_eod_status_u_src_sys EXCEPTION;    -- Exception for status 'U' source system not available
    total_data_count_zero_in_control_t EXCEPTION; -- Exception when SUM(BATCH_TOTAL_REC_COUNT) is Zero

      -- ENQUE MESSAGE VARIABLES --
    agent sys.aq$_agent := sys.aq$_agent(' ', NULL, 0);
    MESSAGE sys.aq$_jms_message;
    enqueue_options dbms_aq.enqueue_options_t;
    message_properties dbms_aq.message_properties_t;
    msgid raw(16);
    json_payload       VARCHAR2(4000); -- JSON payload


BEGIN
json_payload := '{"PSX_BATCH_ID":"' || v_psx_batch_id || '"}';
-- Auditing MASTER_PSX_CUS_BLK_STG table
    INSERT /*+ APPEND */  INTO PROD_CLIPDEDUPE.MASTER_PSX_CUS_BLK_STG_ADT (CUST_UNQ_ID,SOURCE_SYSTEM_CUSTID,CUST_IC,BATCH_ID,CLIENT_REQUESTID,FEED_SYS_ID,SOURCE_SYS_ID,REQUEST_TYPE,SOURCE_SYSTEM,REQUESTED_BY,UNIQUEID,PSX_BATCH_ID,OLD_PSX_BATCH_ID,LCHGTIME,DUIFLAG,EVENTTYPE,INSERT_TIME,PARTITION_NUMBER,NSPKEY,RECORD_ID,ICCLEANING_SPECTRUM,CREATED_FOR,BANK_UCIC,CUST_CREATE_DATE,CUST_FIRST_NAME,CUST_MIDDLE_NAME,CUST_LAST_NAME,CUST_FULL_NAME,NAM_CUST_SHRT,NAME_SALUTATION,GENDER,DOBDOI,MOTHER_NAME,FATHER_NAME,SPOUSE_NAME,EMPLOYER_NAME,UCIC,PAN,PASSPORT,VOTERID,DRIVING_LICENSE_NUMBER,NREGA,TAN,TIN,UDYAM_AADHAR_NO,CKYC,DIN,CIN,GSTIN_1,GSTIN_2,GSTIN_3,GSTIN_4,GSTIN_5,GSTIN_6,GSTIN_7,GSTIN_8,GSTIN_9,GSTIN_10,IEC_NO,LEI,AADHAR_NO,AADHAR_LINKED_STATUS,PASSPORT_DATEOFEXPIRY,DRIVING_LICENSE_DATEOFEXPIRY,NREGA_DATEOFEXPIRY,OVD_STATUS,SHOP_ESTABLISHMENT,HOME_BRANCH_CODE,HOME_BRANCH_DESCRIPTION,FATCA_FLAG,CUSTOMER_TYPE_CODE,CUSTOMER_TYPE_NAME,CUSTOMER_STATUS,CUSTOMER_SEGMENT,CUSTOMER_CATEGORY,ENTITY_TYPE,APPLICANT_TYPE,PEP,GROUPID,KYC_STATUS,DATE_OF_KYCDONE,REKYC_DUEON,RISK_CATEGORY,STAFF_EMPLOYEEID,STAFF_FLAG,YESFIRSTFLG,MINOR_FLAG,NATIONALITY,CONSTITUTION_TYPE,AADHAR_DETAILS,KYC_MODE,EXTRA_NAME1,EXTRA_NAME2,EXTRA_DATE1,EXTRA_DATE2,EXTRA_EQUALITY1,EXTRA_EQUALITY2,EXTRA_EQUALITY3,EXTRA_EQUALITY4,EXTRA_EQUALITY5,EXTRA_EQUALITY6,EXTRA_EQUALITY7,EXTRA_EQUALITY8,EXTRA_EQUALITY9,EXTRA_EQUALITY10,ORIGINATING_PRODUCT,ORIGINATING_CHANNEL,ORIGINATING_STATUS,ORIGINATING_REMARKS,ORIGINATING_LAST_UPDT,ORIGINATING_REJECTED_BY,ADDRESS_TYPE_1,ADDRESS_TYPE_2,ADDRESS_TYPE_3,ADDRESS_TYPE_4,ADDRESS_1,ADDRESS_2,ADDRESS_3,ADDRESS_4,CITY_1,CITY_2,CITY_3,CITY_4,STATE_1,STATE_2,STATE_3,STATE_4,COUNTRY_1,COUNTRY_2,COUNTRY_3,COUNTRY_4,PINCODE_1,PINCODE_2,PINCODE_3,PINCODE_4,EMAIL_TYPE_1,EMAIL_TYPE_2,EMAIL_1,EMAIL_2,PHONE_TYPE_1,PHONE_TYPE_2,PHONE_TYPE_3,PHONE_1,PHONE_2,PHONE_3,ADJACENCYLIST,ISPARTIAL,CLUSTERING_0,CLUSTERING_CNT_0,EQUATION_0,CLUSTERING_1,CLUSTERING_CNT_1,EQUATION_1,CLUSTERING_2,CLUSTERING_CNT_2,EQUATION_2,CLUSTERING_3,CLUSTERING_CNT_3,EQUATION_3) 
    SELECT /*+ enable_parallel_dml parallel(PROD_CLIPDEDUPE.MASTER_PSX_CUS_BLK_STG, 6) */ CUST_UNQ_ID,SOURCE_SYSTEM_CUSTID,CUST_IC,BATCH_ID,CLIENT_REQUESTID,FEED_SYS_ID,SOURCE_SYS_ID,REQUEST_TYPE,SOURCE_SYSTEM,REQUESTED_BY,UNIQUEID,PSX_BATCH_ID,OLD_PSX_BATCH_ID,LCHGTIME,DUIFLAG,EVENTTYPE,INSERT_TIME,PARTITION_NUMBER,NSPKEY,RECORD_ID,ICCLEANING_SPECTRUM,CREATED_FOR,BANK_UCIC,CUST_CREATE_DATE,CUST_FIRST_NAME,CUST_MIDDLE_NAME,CUST_LAST_NAME,CUST_FULL_NAME,NAM_CUST_SHRT,NAME_SALUTATION,GENDER,DOBDOI,MOTHER_NAME,FATHER_NAME,SPOUSE_NAME,EMPLOYER_NAME,UCIC,PAN,PASSPORT,VOTERID,DRIVING_LICENSE_NUMBER,NREGA,TAN,TIN,UDYAM_AADHAR_NO,CKYC,DIN,CIN,GSTIN_1,GSTIN_2,GSTIN_3,GSTIN_4,GSTIN_5,GSTIN_6,GSTIN_7,GSTIN_8,GSTIN_9,GSTIN_10,IEC_NO,LEI,AADHAR_NO,AADHAR_LINKED_STATUS,PASSPORT_DATEOFEXPIRY,DRIVING_LICENSE_DATEOFEXPIRY,NREGA_DATEOFEXPIRY,OVD_STATUS,SHOP_ESTABLISHMENT,HOME_BRANCH_CODE,HOME_BRANCH_DESCRIPTION,FATCA_FLAG,CUSTOMER_TYPE_CODE,CUSTOMER_TYPE_NAME,CUSTOMER_STATUS,CUSTOMER_SEGMENT,CUSTOMER_CATEGORY,ENTITY_TYPE,APPLICANT_TYPE,PEP,GROUPID,KYC_STATUS,DATE_OF_KYCDONE,REKYC_DUEON,RISK_CATEGORY,STAFF_EMPLOYEEID,STAFF_FLAG,YESFIRSTFLG,MINOR_FLAG,NATIONALITY,CONSTITUTION_TYPE,AADHAR_DETAILS,KYC_MODE,EXTRA_NAME1,EXTRA_NAME2,EXTRA_DATE1,EXTRA_DATE2,EXTRA_EQUALITY1,EXTRA_EQUALITY2,EXTRA_EQUALITY3,EXTRA_EQUALITY4,EXTRA_EQUALITY5,EXTRA_EQUALITY6,EXTRA_EQUALITY7,EXTRA_EQUALITY8,EXTRA_EQUALITY9,EXTRA_EQUALITY10,ORIGINATING_PRODUCT,ORIGINATING_CHANNEL,ORIGINATING_STATUS,ORIGINATING_REMARKS,ORIGINATING_LAST_UPDT,ORIGINATING_REJECTED_BY,ADDRESS_TYPE_1,ADDRESS_TYPE_2,ADDRESS_TYPE_3,ADDRESS_TYPE_4,ADDRESS_1,ADDRESS_2,ADDRESS_3,ADDRESS_4,CITY_1,CITY_2,CITY_3,CITY_4,STATE_1,STATE_2,STATE_3,STATE_4,COUNTRY_1,COUNTRY_2,COUNTRY_3,COUNTRY_4,PINCODE_1,PINCODE_2,PINCODE_3,PINCODE_4,EMAIL_TYPE_1,EMAIL_TYPE_2,EMAIL_1,EMAIL_2,PHONE_TYPE_1,PHONE_TYPE_2,PHONE_TYPE_3,PHONE_1,PHONE_2,PHONE_3,ADJACENCYLIST,ISPARTIAL,CLUSTERING_0,CLUSTERING_CNT_0,EQUATION_0,CLUSTERING_1,CLUSTERING_CNT_1,EQUATION_1,CLUSTERING_2,CLUSTERING_CNT_2,EQUATION_2,CLUSTERING_3,CLUSTERING_CNT_3,EQUATION_3  FROM PROD_CLIPDEDUPE.MASTER_PSX_CUS_BLK_STG;

     COMMIT;

    -- Truncating MASTER_PSX_CUS_BLK_STG table
    EXECUTE IMMEDIATE 'TRUNCATE TABLE PROD_CLIPDEDUPE.MASTER_PSX_CUS_BLK_STG';

    -- Auditing PSXIDS_DT_2_HASHING table
    INSERT /*+ APPEND */  INTO PROD_CLIPDEDUPE.PSXIDS_DT_2_HASHING_ADT (PSX_ID,DUI_FLAG,BATCH_ID,PSX_BATCH_ID,ISCLUSTERREFLOW,RECORD_ID,CUST_UNQ_ID) 
    SELECT /*+ enable_parallel_dml parallel(PROD_CLIPDEDUPE.PSXIDS_DT_2_HASHING, 1) */ PSX_ID,DUI_FLAG,BATCH_ID,PSX_BATCH_ID,ISCLUSTERREFLOW,RECORD_ID,CUST_UNQ_ID FROM PROD_CLIPDEDUPE.PSXIDS_DT_2_HASHING;

     COMMIT;

    -- Truncating PSXIDS_DT_2_HASHING table
    EXECUTE IMMEDIATE 'TRUNCATE TABLE PROD_CLIPDEDUPE.PSXIDS_DT_2_HASHING';
    
    -- Truncating PSX_CLUSTER_CROSS_REF_EOD_ADT table
    EXECUTE IMMEDIATE 'TRUNCATE TABLE PROD_CLIPDEDUPE.PSX_CLUSTER_CROSS_REF_T_EOD_ADT DROP STORAGE';
    
    -- Auditing PSX_CLUSTER_CROSS_REF_T_EOD_ADT table
    INSERT /*+ APPEND */ INTO PSX_CLUSTER_CROSS_REF_T_EOD_ADT SELECT /*+ PARALLEL(4) */ * FROM PSX_CLUSTER_CROSS_REF_T;

    COMMIT;
    
    -- Auditing PSX_CLUSTER_CROSS_REF_T_EOD_ADT table
    INSERT /*+ APPEND */  INTO PSX_CLUSTER_AUDIT_T_EOD_ADT SELECT /*+ PARALLEL(4) */ * FROM PSX_CLUSTER_AUDIT_T;

    -- Truncating PSX_CLUSTER_AUDIT_T table
    EXECUTE IMMEDIATE 'TRUNCATE TABLE PSX_CLUSTER_AUDIT_T DROP STORAGE';
    
    COMMIT;
    
    -- Auditing PSX_CUSTOMER_DATA_INCREMENTAL table
    INSERT /*+ APPEND */  INTO PROD_CLIPDEDUPE.PSX_CUSTOMER_DATA_INCREMENTAL_ADT( SOURCE_SYSTEM,SOURCE_SYSTEM_CUSTID,INSERT_TS,SOURCE_SYSTEM_DATE,BATCH_ID,CUST_IC,CREATED_FOR,BANK_UCIC,CUST_CREATE_DATE,CUST_FIRST_NAME,CUST_MIDDLE_NAME,CUST_LAST_NAME,CUST_FULL_NAME,NAM_CUST_SHRT,NAME_SALUTATION,GENDER,DOBDOI,MOTHER_NAME,FATHER_NAME,SPOUSE_NAME,EMPLOYER_NAME,PAN,PASSPORT,VOTERID,DRIVING_LICENSE_NUMBER,NREGA,TAN,TIN,UDYAM_AADHAR_NO,CKYC,DIN,CIN,GSTIN_1,GSTIN_2,GSTIN_3,GSTIN_4,GSTIN_5,GSTIN_6,GSTIN_7,GSTIN_8,GSTIN_9,GSTIN_10,IEC_NO,LEI,ADDRESS_TYPE_1,ADDRESS_TYPE_2,ADDRESS_TYPE_3,ADDRESS_TYPE_4,ADDRESS_1,REQUESTED_BY,ADDRESS_2,ADDRESS_3,ADDRESS_4,CITY_1,CITY_2,CITY_3,CITY_4,STATE_1,STATE_2,STATE_3,STATE_4,COUNTRY_1,COUNTRY_2,COUNTRY_3,COUNTRY_4,PINCODE_1,PINCODE_2,PINCODE_3,PINCODE_4,EMAIL_TYPE_1,EMAIL_TYPE_2,EMAIL_1,EMAIL_2,PHONE_TYPE_1,PHONE_TYPE_2,PHONE_TYPE_3,PHONE_1,PHONE_2,PHONE_3,AADHAR_NO,AADHAR_LINKED_STATUS,PASSPORT_DATEOFEXPIRY,DRIVING_LICENSE_DATEOFEXPIRY,NREGA_DATEOFEXPIRY,OVD_STATUS,SHOP_ESTABLISHMENT,HOME_BRANCH_CODE,HOME_BRANCH_DESCRIPTION,FATCA_FLAG,CUSTOMER_TYPE_CODE,CUSTOMER_TYPE_NAME,CUSTOMER_STATUS,CUSTOMER_SEGMENT,CUSTOMER_CATEGORY,ENTITY_TYPE,APPLICANT_TYPE,PEP,GROUPID,KYC_STATUS,DATE_OF_KYCDONE,REKYC_DUEON,RISK_CATEGORY,STAFF_EMPLOYEEID,STAFF_FLAG,YESFIRSTFLG,MINOR_FLAG,NATIONALITY,CONSTITUTION_TYPE,AADHAR_DETAILS,KYC_MODE,EXTRA_NAME1,EXTRA_NAME2,EXTRA_DATE1,EXTRA_DATE2,EXTRA_EQUALITY1,EXTRA_EQUALITY2,EXTRA_EQUALITY3,EXTRA_EQUALITY4,EXTRA_EQUALITY5,EXTRA_EQUALITY6,EXTRA_EQUALITY7,EXTRA_EQUALITY8,EXTRA_EQUALITY9,EXTRA_EQUALITY10,ORIGINATING_PRODUCT,ORIGINATING_CHANNEL,ORIGINATING_STATUS,ORIGINATING_REMARKS,ORIGINATING_LAST_UPDT,ORIGINATING_REJECTED_BY,PSX_BATCH_ID,CUST_UNQ_ID,SOURCE_SYSTEM_ID,ERROR_DESCRIPTION,PSX_UCIC) 
    SELECT /*+ enable_parallel_dml parallel(PROD_CLIPDEDUPE.PSX_CUSTOMER_DATA_INCREMENTAL, 1) */ SOURCE_SYSTEM,SOURCE_SYSTEM_CUSTID,INSERT_TS,SOURCE_SYSTEM_DATE,BATCH_ID,CUST_IC,CREATED_FOR,BANK_UCIC,CUST_CREATE_DATE,CUST_FIRST_NAME,CUST_MIDDLE_NAME,CUST_LAST_NAME,CUST_FULL_NAME,NAM_CUST_SHRT,NAME_SALUTATION,GENDER,DOBDOI,MOTHER_NAME,FATHER_NAME,SPOUSE_NAME,EMPLOYER_NAME,PAN,PASSPORT,VOTERID,DRIVING_LICENSE_NUMBER,NREGA,TAN,TIN,UDYAM_AADHAR_NO,CKYC,DIN,CIN,GSTIN_1,GSTIN_2,GSTIN_3,GSTIN_4,GSTIN_5,GSTIN_6,GSTIN_7,GSTIN_8,GSTIN_9,GSTIN_10,IEC_NO,LEI,ADDRESS_TYPE_1,ADDRESS_TYPE_2,ADDRESS_TYPE_3,ADDRESS_TYPE_4,ADDRESS_1,REQUESTED_BY,ADDRESS_2,ADDRESS_3,ADDRESS_4,CITY_1,CITY_2,CITY_3,CITY_4,STATE_1,STATE_2,STATE_3,STATE_4,COUNTRY_1,COUNTRY_2,COUNTRY_3,COUNTRY_4,PINCODE_1,PINCODE_2,PINCODE_3,PINCODE_4,EMAIL_TYPE_1,EMAIL_TYPE_2,EMAIL_1,EMAIL_2,PHONE_TYPE_1,PHONE_TYPE_2,PHONE_TYPE_3,PHONE_1,PHONE_2,PHONE_3,AADHAR_NO,AADHAR_LINKED_STATUS,PASSPORT_DATEOFEXPIRY,DRIVING_LICENSE_DATEOFEXPIRY,NREGA_DATEOFEXPIRY,OVD_STATUS,SHOP_ESTABLISHMENT,HOME_BRANCH_CODE,HOME_BRANCH_DESCRIPTION,FATCA_FLAG,CUSTOMER_TYPE_CODE,CUSTOMER_TYPE_NAME,CUSTOMER_STATUS,CUSTOMER_SEGMENT,CUSTOMER_CATEGORY,ENTITY_TYPE,APPLICANT_TYPE,PEP,GROUPID,KYC_STATUS,DATE_OF_KYCDONE,REKYC_DUEON,RISK_CATEGORY,STAFF_EMPLOYEEID,STAFF_FLAG,YESFIRSTFLG,MINOR_FLAG,NATIONALITY,CONSTITUTION_TYPE,AADHAR_DETAILS,KYC_MODE,EXTRA_NAME1,EXTRA_NAME2,EXTRA_DATE1,EXTRA_DATE2,EXTRA_EQUALITY1,EXTRA_EQUALITY2,EXTRA_EQUALITY3,EXTRA_EQUALITY4,EXTRA_EQUALITY5,EXTRA_EQUALITY6,EXTRA_EQUALITY7,EXTRA_EQUALITY8,EXTRA_EQUALITY9,EXTRA_EQUALITY10,ORIGINATING_PRODUCT,ORIGINATING_CHANNEL,ORIGINATING_STATUS,ORIGINATING_REMARKS,ORIGINATING_LAST_UPDT,ORIGINATING_REJECTED_BY,PSX_BATCH_ID,CUST_UNQ_ID,SOURCE_SYSTEM_ID,ERROR_DESCRIPTION,PSX_UCIC FROM PROD_CLIPDEDUPE.PSX_CUSTOMER_DATA_INCREMENTAL;

     COMMIT;

    -- Truncating PSX_CUSTOMER_DATA_INCREMENTAL table
    EXECUTE IMMEDIATE 'TRUNCATE TABLE PROD_CLIPDEDUPE.PSX_CUSTOMER_DATA_INCREMENTAL';

-- Updating the PSX_BATCH_ID in PSX_EOD_CONTROL_T
UPDATE /*+ PARALLEL(1) */ PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T set 
PSX_BATCH_ID = v_psx_batch_id where batch_id = v_batch_id AND DATA_CATEGORY='CUSTOMER' AND EOD_STATUS='P';

COMMIT;

-- Getting the count from YBL_CUSTOMER_DATA_INCREMENTAL with the input BATCH_ID
SELECT /*+ enable_parallel_dml parallel(6) */ COUNT(*) INTO input_batchid_cnt_in_ybl_t FROM PROD_PSX_DEDUPE_STAGING.YBL_CUSTOMER_DATA_INCREMENTAL 
WHERE BATCH_ID = v_batch_id;
COMMIT;
-- Raising the exception when the input BATCH_ID not found in YBL_CUSTOMER_DATA_INCREMENTAL
IF input_batchid_cnt_in_ybl_t = 0 THEN
   UPDATE /*+ PARALLEL(1) */ PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T SET EOD_STATUS='E', ERROR_DESCRIPTION='BATCH_ID not found in YBL_CUSTOMER_DATA_INCREMENTAL table'
   WHERE BATCH_ID = v_batch_id AND DATA_CATEGORY='CUSTOMER';

COMMIT;

   RAISE batchid_not_found;
END IF;


-- Validating the SOURCE_SYSTEM against SOURCE_SYSTEM_MASTER
   UPDATE /*+ PARALLEL(1) */ PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T t
SET t.EOD_STATUS = 'E',
    t.ERROR_DESCRIPTION = 'Invalid Source System Name'
WHERE t.BATCH_ID = v_batch_id AND DATA_CATEGORY='CUSTOMER' AND EOD_STATUS='P'
AND (t.SOURCE_SYSTEM IS NULL OR
     NOT EXISTS (
        SELECT 1 
        FROM PROD_CLIPDEDUPE.SOURCE_SYSTEM_MASTER m
        WHERE t.SOURCE_SYSTEM = m.SOURCE_SYSTEM_NAME
     ));
Commit;

    -- Checking if any invalid sources were updated
    IF SQL%ROWCOUNT > 0 THEN
        -- Commit the changes for invalid source system updates
        COMMIT;
        RAISE invalid_source_system;  -- Raise exception if invalid source system exists
    ELSE
        COMMIT; -- Only commit if no errors were found
    END IF;

	-- Updating EOD_STATUS & ERROR_DESCRIPTION whose BATCH_TOTAL_REC_COUNT = 0 in PSX_EOD_CONTROL_T
	UPDATE /*+ PARALLEL(1) */ PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T
    SET
    EOD_STATUS = CASE
                    WHEN BATCH_TOTAL_REC_COUNT = 0 THEN 'E'
                    ELSE EOD_STATUS
                 END,
    ERROR_DESCRIPTION = CASE
                           WHEN BATCH_TOTAL_REC_COUNT = 0 THEN 'No Data Available'
                           ELSE ERROR_DESCRIPTION
                        END
    WHERE BATCH_ID = v_batch_id AND DATA_CATEGORY='CUSTOMER' AND EOD_STATUS='P';

    COMMIT;

    -- Getting the total count from PSX_EOD_CONTROL_T for the given v_batch_id
    SELECT /*+ PARALLEL(1) */ COUNT(*)
    INTO control_table_count
    FROM PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T
    WHERE BATCH_ID = v_batch_id AND DATA_CATEGORY='CUSTOMER' AND EOD_STATUS='P';

    -- Getting the distinct count of SOURCE_SYSTEM from YBL_CUSTOMER_DATA_INCREMENTAL for the same v_batch_id
    SELECT /*+ PARALLEL(1) */ COUNT(DISTINCT SOURCE_SYSTEM)
    INTO incremental_table_distinct_count
    FROM PROD_PSX_DEDUPE_STAGING.YBL_CUSTOMER_DATA_INCREMENTAL t3
    WHERE t3.BATCH_ID = v_batch_id;

    -- Comparing the total counts between the two tables for the specific v_batch_id
    IF control_table_count != incremental_table_distinct_count THEN
        -- Update only records for the specific v_batch_id where counts mismatch
        UPDATE /*+ PARALLEL(1) */ PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T
        SET EOD_STATUS = 'E',
            ERROR_DESCRIPTION = 'Source System Counts are not the same between PSX_EOD_CONTROL_T and YBL_CUSTOMER_DATA_INCREMENTAL'
        WHERE BATCH_ID = v_batch_id AND DATA_CATEGORY='CUSTOMER' AND EOD_STATUS='P';  -- Strictly limiting to this v_batch_id

        COMMIT; -- Commit the changes
        RAISE count_mismatch; -- Raise the `count_mismatch` exception
    END IF;


    -- Getting the SUM of BATCH_TOTAL_REC_COUNT for the specific v_batch_id
    SELECT SUM(BATCH_TOTAL_REC_COUNT)
    INTO sum_batch_total_rec_count
    FROM PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T
    WHERE BATCH_ID = v_batch_id AND DATA_CATEGORY='CUSTOMER' AND EOD_STATUS='P';

    -- Raising the exception when SUM(BATCH_TOTAL_REC_COUNT) is equal to zero
   IF sum_batch_total_rec_count = 0 THEN
   UPDATE /*+ PARALLEL(1) */ PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T
   SET EOD_STATUS = 'E',
   ERROR_DESCRIPTION = 'No Data Avaialbe for CLIP EOD Process'
   WHERE BATCH_ID = v_batch_id AND DATA_CATEGORY='CUSTOMER' AND EOD_STATUS='P';  

        COMMIT; -- Commit the changes
   RAISE total_data_count_zero_in_control_t;
   END IF;

    -- Comparing individual SOURCE_SYSTEM data counts for the specific v_batch_id
    FOR rec IN (
        SELECT /*+ PARALLEL(1) */ SOURCE_SYSTEM, BATCH_TOTAL_REC_COUNT
        FROM PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T
        WHERE BATCH_ID = v_batch_id AND DATA_CATEGORY='CUSTOMER' AND EOD_STATUS='P'
    )
    LOOP
        -- Getting the actual count from YBL_CUSTOMER_DATA_INCREMENTAL for the same SOURCE_SYSTEM and v_batch_id
        SELECT /*+ PARALLEL(1) */ COUNT(*)
        INTO actual_count
        FROM PROD_PSX_DEDUPE_STAGING.YBL_CUSTOMER_DATA_INCREMENTAL t6
        WHERE BATCH_ID = v_batch_id
        AND SOURCE_SYSTEM = rec.SOURCE_SYSTEM;

        -- Checking if BATCH_TOTAL_REC_COUNT matches the actual count
        IF rec.BATCH_TOTAL_REC_COUNT != actual_count THEN
            -- If counts mismatch, update the EOD_STATUS to 'E' and add an error message
            UPDATE /*+ PARALLEL(1) */ PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T
            SET EOD_STATUS = 'E',
                ERROR_DESCRIPTION = rec.SOURCE_SYSTEM || ' data counts are mismatched'
            WHERE BATCH_ID = v_batch_id
            AND SOURCE_SYSTEM = rec.SOURCE_SYSTEM
            AND DATA_CATEGORY='CUSTOMER'
            AND EOD_STATUS='P';

        ELSE
            -- If counts match, update the EOD_STATUS to 'U'
            UPDATE /*+ PARALLEL(1) */ PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T
            SET EOD_STATUS = 'U'
            WHERE BATCH_ID = v_batch_id
            AND SOURCE_SYSTEM = rec.SOURCE_SYSTEM
            AND DATA_CATEGORY='CUSTOMER'
            AND EOD_STATUS='P';
        END IF;
    END LOOP;

 COMMIT;

-- Getting the count of Source Systems which are having EOD_STATUS as 'U'
-- Atleast one Source System should have EOD_STATUS as 'U' to proceed to next stage
SELECT /*+ PARALLEL(1) */ COUNT(*) INTO eod_status_u_src_sys_count FROM PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T 
WHERE EOD_STATUS='U' AND BATCH_ID = v_batch_id;

-- Raising the exception when there is no Source System is having EOD_STATUS as 'U'
IF eod_status_u_src_sys_count = 0 THEN
   RAISE no_eod_status_u_src_sys;
END IF;

    -- Set the output status to 'C' for successful completion
    o_status := 'C';  -- Set success status at the end of the procedure

EXCEPTION
    -- Catching exceptions
    WHEN batchid_not_found THEN
        o_status := 'E';  -- Set error status for batchid not found
        UPDATE PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T SET PSX_BATCH_ID = v_psx_batch_id WHERE BATCH_ID = v_batch_id AND DATA_CATEGORY='ACCOUNTS';
        MESSAGE := sys.aq$_jms_message.construct(dbms_aq.JMS_TEXT_MESSAGE);
    message.set_replyto(agent);
    message.set_type('tkaqpet2');
    message.set_userid('CLIPDEDUPE');
    message.set_appid('plsql_enq');
    message.set_groupid('st');
    message.set_groupseq(1);
    message.set_Short_Property('systemId',1);
    message.set_Long_Property('psxIdBatchId',v_psx_batch_id);  -- Use the input batch ID
    message.set_Short_Property('purposeId',99);
    message.set_string_property('PSX_BATCH_ID', v_psx_batch_id); 
    message.set_text(json_payload);


    DBMS_AQ.ENQUEUE(
        queue_name => 'PROD_PRIME360DEDUPE.PSX_EOD_QUEUE',
        enqueue_options => enqueue_options,
        message_properties => message_properties,
        payload => message,
        msgid => msgid
    );
    COMMIT;
        RETURN;           -- Exit the procedure
    WHEN invalid_source_system THEN
        o_status := 'E';  -- Set error status for invalid source system
        UPDATE PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T SET PSX_BATCH_ID = v_psx_batch_id WHERE BATCH_ID = v_batch_id AND DATA_CATEGORY='ACCOUNTS';
        MESSAGE := sys.aq$_jms_message.construct(dbms_aq.JMS_TEXT_MESSAGE);
    message.set_replyto(agent);
    message.set_type('tkaqpet2');
    message.set_userid('CLIPDEDUPE');
    message.set_appid('plsql_enq');
    message.set_groupid('st');
    message.set_groupseq(1);
    message.set_Short_Property('systemId',1);
    message.set_Long_Property('psxIdBatchId',v_psx_batch_id);  -- Use the input batch ID
    message.set_Short_Property('purposeId',99);
    message.set_string_property('PSX_BATCH_ID', v_psx_batch_id); 
    message.set_text(json_payload);


    DBMS_AQ.ENQUEUE(
        queue_name => 'PROD_PRIME360DEDUPE.PSX_EOD_QUEUE',
        enqueue_options => enqueue_options,
        message_properties => message_properties,
        payload => message,
        msgid => msgid
    );
    COMMIT;
        RETURN;           -- Exit the procedure
    WHEN count_mismatch THEN
        o_status := 'E';  -- Set error status for count mismatch
        UPDATE PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T SET PSX_BATCH_ID = v_psx_batch_id WHERE BATCH_ID = v_batch_id AND DATA_CATEGORY='ACCOUNTS';
       MESSAGE := sys.aq$_jms_message.construct(dbms_aq.JMS_TEXT_MESSAGE);
    message.set_replyto(agent);
    message.set_type('tkaqpet2');
    message.set_userid('CLIPDEDUPE');
    message.set_appid('plsql_enq');
    message.set_groupid('st');
    message.set_groupseq(1);
    message.set_Short_Property('systemId',1);
    message.set_Long_Property('psxIdBatchId',v_psx_batch_id);  -- Use the input batch ID
    message.set_Short_Property('purposeId',99);
    message.set_string_property('PSX_BATCH_ID', v_psx_batch_id); 
    message.set_text(json_payload);


    DBMS_AQ.ENQUEUE(
        queue_name => 'PROD_PRIME360DEDUPE.PSX_EOD_QUEUE',
        enqueue_options => enqueue_options,
        message_properties => message_properties,
        payload => message,
        msgid => msgid
    );
    COMMIT;
       RETURN;           -- Exit the procedure
    WHEN total_data_count_zero_in_control_t THEN
        o_status := 'E';  -- Set error status for count mismatch
        UPDATE PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T SET PSX_BATCH_ID = v_psx_batch_id WHERE BATCH_ID = v_batch_id AND DATA_CATEGORY='ACCOUNTS';
        MESSAGE := sys.aq$_jms_message.construct(dbms_aq.JMS_TEXT_MESSAGE);
    message.set_replyto(agent);
    message.set_type('tkaqpet2');
    message.set_userid('CLIPDEDUPE');
    message.set_appid('plsql_enq');
    message.set_groupid('st');
    message.set_groupseq(1);
    message.set_Short_Property('systemId',1);
    message.set_Long_Property('psxIdBatchId',v_psx_batch_id);  -- Use the input batch ID
    message.set_Short_Property('purposeId',99);
    message.set_string_property('PSX_BATCH_ID', v_psx_batch_id); 
    message.set_text(json_payload);


    DBMS_AQ.ENQUEUE(
        queue_name => 'PROD_PRIME360DEDUPE.PSX_EOD_QUEUE',
        enqueue_options => enqueue_options,
        message_properties => message_properties,
        payload => message,
        msgid => msgid
    );
    COMMIT;
        RETURN;           -- Exit the procedure    
    WHEN no_eod_status_u_src_sys THEN
        o_status := 'E';  -- Set error status as none of the source systems are having eod_status 'U' 
        UPDATE PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T SET PSX_BATCH_ID = v_psx_batch_id WHERE BATCH_ID = v_batch_id AND DATA_CATEGORY='ACCOUNTS';


        -- Enqueue PSX_EOD_QUEUE
    MESSAGE := sys.aq$_jms_message.construct(dbms_aq.JMS_TEXT_MESSAGE);
    message.set_replyto(agent);
    message.set_type('tkaqpet2');
    message.set_userid('CLIPDEDUPE');
    message.set_appid('plsql_enq');
    message.set_groupid('st');
    message.set_groupseq(1);
    message.set_Short_Property('systemId',1);
    message.set_Long_Property('psxIdBatchId',v_psx_batch_id);  -- Use the input batch ID
    message.set_Short_Property('purposeId',99);
    message.set_string_property('PSX_BATCH_ID', v_psx_batch_id); 
    message.set_text(json_payload);


    DBMS_AQ.ENQUEUE(
        queue_name => 'PROD_PRIME360DEDUPE.PSX_EOD_QUEUE',
        enqueue_options => enqueue_options,
        message_properties => message_properties,
        payload => message,
        msgid => msgid
    );
    COMMIT;
   RETURN;   -- Exit the procedure
    UPDATE PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T SET PSX_BATCH_ID = v_psx_batch_id WHERE BATCH_ID = v_batch_id AND DATA_CATEGORY='CUSTOMER';
   o_status := 'E';
                 o_descripition := 'Error in the PSX_VALIDATE_COUNT PROCEDURE';
                 o_sqlerror := 'Error: ' || SQLERRM || ' at ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;

END;

==================================================================================================================

3. PSX_CUSTOMER_EOD_DATA_PULL

create or replace PROCEDURE PSX_CUSTOMER_EOD_DATA_PULL (
    v_batch_id IN VARCHAR2, 
    v_psx_batch_id IN VARCHAR2,
    o_status OUT VARCHAR2, -- Output parameter for status
    p_descripition out varchar2, -- descripition
    p_sqlerror out varchar2 -- sql error
) AS
BEGIN
    -- Initialize output status to 'C' for success
    o_status := 'C'; 

    -- Check if v_psx_batch_id is not null
    IF v_psx_batch_id IS NOT NULL THEN
        BEGIN

            -- Importing data from YBL_CUSTOMER_DATA_INCREMENTAL to PSX_CUSTOMER_DATA_INCREMENTAL
            EXECUTE IMMEDIATE 'INSERT /*+ APPEND */ INTO PSX_CUSTOMER_DATA_INCREMENTAL 
    (SOURCE_SYSTEM, SOURCE_SYSTEM_CUSTID, SOURCE_SYSTEM_DATE, BATCH_ID, PSX_BATCH_ID, CUST_IC, CREATED_FOR, 
    BANK_UCIC, CUST_CREATE_DATE, CUST_FIRST_NAME, CUST_MIDDLE_NAME, CUST_LAST_NAME, CUST_FULL_NAME, 
    NAM_CUST_SHRT, NAME_SALUTATION, GENDER, DOBDOI, MOTHER_NAME, FATHER_NAME, SPOUSE_NAME, EMPLOYER_NAME, PAN, 
    PASSPORT, VOTERID, DRIVING_LICENSE_NUMBER, NREGA, TAN, TIN, UDYAM_AADHAR_NO, CKYC, DIN, CIN, GSTIN_1, 
    GSTIN_2, GSTIN_3, GSTIN_4, GSTIN_5, GSTIN_6, GSTIN_7, GSTIN_8, GSTIN_9, GSTIN_10, IEC_NO, LEI, 
    ADDRESS_TYPE_1, ADDRESS_TYPE_2, ADDRESS_TYPE_3, ADDRESS_TYPE_4, ADDRESS_1, ADDRESS_2, ADDRESS_3, 
    ADDRESS_4, CITY_1, CITY_2, CITY_3, CITY_4, STATE_1, STATE_2, STATE_3, STATE_4, COUNTRY_1, COUNTRY_2, 
    COUNTRY_3, COUNTRY_4, PINCODE_1, PINCODE_2, PINCODE_3, PINCODE_4, EMAIL_TYPE_1, EMAIL_TYPE_2, EMAIL_1, 
    EMAIL_2, PHONE_TYPE_1, PHONE_TYPE_2, PHONE_TYPE_3, PHONE_1, PHONE_2, PHONE_3, AADHAR_NO, 
    AADHAR_LINKED_STATUS, PASSPORT_DATEOFEXPIRY, DRIVING_LICENSE_DATEOFEXPIRY, NREGA_DATEOFEXPIRY, OVD_STATUS, 
    SHOP_ESTABLISHMENT, HOME_BRANCH_CODE, HOME_BRANCH_DESCRIPTION, FATCA_FLAG, CUSTOMER_TYPE_CODE, 
    CUSTOMER_TYPE_NAME, CUSTOMER_STATUS, CUSTOMER_SEGMENT, CUSTOMER_CATEGORY, ENTITY_TYPE, SOLEPROP_F, CORPORATE_F, APPLICANT_TYPE, 
    PEP, GROUPID, KYC_STATUS, DATE_OF_KYCDONE, REKYC_DUEON, RISK_CATEGORY, STAFF_EMPLOYEEID, STAFF_FLAG, 
    YESFIRSTFLG, MINOR_FLAG, NATIONALITY, CONSTITUTION_TYPE, AADHAR_DETAILS, KYC_MODE, EXTRA_NAME1, 
    EXTRA_NAME2,EXTRA_NAME3, EXTRA_DATE1, EXTRA_DATE2,EXTRA_DATE3, EXTRA_EQUALITY1, EXTRA_EQUALITY2, EXTRA_EQUALITY3, EXTRA_EQUALITY4, 
    EXTRA_EQUALITY5, EXTRA_EQUALITY6, EXTRA_EQUALITY7, EXTRA_EQUALITY8, EXTRA_EQUALITY9, EXTRA_EQUALITY10, 
    ORIGINATING_PRODUCT, ORIGINATING_CHANNEL, ORIGINATING_STATUS, ORIGINATING_REMARKS, ORIGINATING_LAST_UPDT, 
    ORIGINATING_REJECTED_BY, INSERT_TS)
    SELECT /*+ enable_parallel_dml parallel(YBL,6) */ YBL.SOURCE_SYSTEM, YBL.SOURCE_SYSTEM_CUSTID, YBL.SOURCE_SYSTEM_DATE, YBL.BATCH_ID, ''' || v_psx_batch_id || ''' AS PSX_BATCH_ID, YBL.CUST_IC, YBL.CREATED_FOR, YBL.BANK_UCIC, YBL.CUST_CREATE_DATE, YBL.CUST_FIRST_NAME, YBL.CUST_MIDDLE_NAME, YBL.CUST_LAST_NAME, YBL.CUST_FULL_NAME, 
    YBL.NAM_CUST_SHRT, YBL.NAME_SALUTATION, YBL.GENDER, YBL.DOBDOI, YBL.MOTHER_NAME, YBL.FATHER_NAME, YBL.SPOUSE_NAME, 
    YBL.EMPLOYER_NAME, YBL.PAN, YBL.PASSPORT, YBL.VOTERID, YBL.DRIVING_LICENSE_NUMBER, YBL.NREGA, YBL.TAN, YBL.TIN, YBL.UDYAM_AADHAR_NO, 
    YBL.CKYC, YBL.DIN, YBL.CIN, YBL.GSTIN_1, YBL.GSTIN_2, YBL.GSTIN_3, YBL.GSTIN_4, YBL.GSTIN_5, YBL.GSTIN_6, YBL.GSTIN_7, YBL.GSTIN_8, 
    YBL.GSTIN_9, YBL.GSTIN_10, YBL.IEC_NO, YBL.LEI, YBL.ADDRESS_TYPE_1, YBL.ADDRESS_TYPE_2, YBL.ADDRESS_TYPE_3, YBL.ADDRESS_TYPE_4, 
    YBL.ADDRESS_1, YBL.ADDRESS_2, YBL.ADDRESS_3, YBL.ADDRESS_4, YBL.CITY_1, YBL.CITY_2, YBL.CITY_3, YBL.CITY_4, YBL.STATE_1, YBL.STATE_2, 
    YBL.STATE_3, YBL.STATE_4, YBL.COUNTRY_1, YBL.COUNTRY_2, YBL.COUNTRY_3, YBL.COUNTRY_4, YBL.PINCODE_1, YBL.PINCODE_2, YBL.PINCODE_3, 
    YBL.PINCODE_4, YBL.EMAIL_TYPE_1, YBL.EMAIL_TYPE_2, YBL.EMAIL_1, YBL.EMAIL_2, YBL.PHONE_TYPE_1, YBL.PHONE_TYPE_2, YBL.PHONE_TYPE_3, 
    YBL.PHONE_1, YBL.PHONE_2, YBL.PHONE_3, YBL.AADHAR_NO, YBL.AADHAR_LINKED_STATUS, YBL.PASSPORT_DATEOFEXPIRY, 
    YBL.DRIVING_LICENSE_DATEOFEXPIRY, YBL.NREGA_DATEOFEXPIRY, YBL.OVD_STATUS, YBL.SHOP_ESTABLISHMENT, YBL.HOME_BRANCH_CODE, 
    YBL.HOME_BRANCH_DESCRIPTION, YBL.FATCA_FLAG, YBL.CUSTOMER_TYPE_CODE, YBL.CUSTOMER_TYPE_NAME, YBL.CUSTOMER_STATUS, 
    YBL.CUSTOMER_SEGMENT, YBL.CUSTOMER_CATEGORY, YBL.ENTITY_TYPE,YBL.ENTITY_TYPE, YBL.ENTITY_TYPE, YBL.APPLICANT_TYPE, YBL.PEP, YBL.GROUPID, YBL.KYC_STATUS, 
    YBL.DATE_OF_KYCDONE, YBL.REKYC_DUEON, YBL.RISK_CATEGORY, YBL.STAFF_EMPLOYEEID, YBL.STAFF_FLAG, YBL.YESFIRSTFLG, YBL.MINOR_FLAG, 
    YBL.NATIONALITY, YBL.CONSTITUTION_TYPE, YBL.AADHAR_DETAILS, YBL.KYC_MODE, YBL.EXTRA_NAME1, YBL.EXTRA_NAME2,YBL.CUST_FULL_NAME,YBL.EXTRA_DATE1, 
    YBL.EXTRA_DATE2,CASE 
        WHEN TO_CHAR(YBL.DOBDOI, ''DD-MM'') IN (''01-01'', ''01-06'') THEN NULL
        ELSE YBL.DOBDOI
    END, YBL.EXTRA_EQUALITY1, YBL.EXTRA_EQUALITY2, YBL.EXTRA_EQUALITY3, YBL.EXTRA_EQUALITY4, YBL.EXTRA_EQUALITY5, 
    YBL.EXTRA_EQUALITY6, YBL.EXTRA_EQUALITY7, YBL.EXTRA_EQUALITY8, YBL.EXTRA_EQUALITY9, YBL.EXTRA_EQUALITY10, YBL.ORIGINATING_PRODUCT, 
    YBL.ORIGINATING_CHANNEL, YBL.ORIGINATING_STATUS, YBL.ORIGINATING_REMARKS, YBL.ORIGINATING_LAST_UPDT, 
    YBL.ORIGINATING_REJECTED_BY, YBL.INSERT_TS FROM PROD_PSX_DEDUPE_STAGING.YBL_CUSTOMER_DATA_INCREMENTAL YBL 
    JOIN PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T EOD ON YBL.BATCH_ID = EOD.BATCH_ID 
    WHERE YBL.BATCH_ID = ''' || v_batch_id || ''' AND EOD.EOD_STATUS = ''U'' 
    AND EOD.DATA_CATEGORY = ''CUSTOMER'' AND YBL.SOURCE_SYSTEM = EOD.SOURCE_SYSTEM';

            COMMIT;

            -- Updating SOURCE_SYSTEM_ID in PSX_CUSTOMER_DATA_INCREMENTAL with SOURCE_SYSTEM_MASTER table
            UPDATE /*+ enable_parallel_dml parallel(6) */ PSX_CUSTOMER_DATA_INCREMENTAL CDI
            SET CDI.SOURCE_SYSTEM_ID = (SELECT SSM.SOURCE_SYSTEM_ID
                                        FROM SOURCE_SYSTEM_MASTER SSM
                                        WHERE SSM.SOURCE_SYSTEM_NAME = CDI.SOURCE_SYSTEM);
            COMMIT;

            -- Update CUST_UNQ_ID by appending SOURCE_SYSTEM_ID and SOURCE_SYSTEM_CUSTID
            UPDATE /*+ enable_parallel_dml parallel(6) */ PSX_CUSTOMER_DATA_INCREMENTAL
            SET CUST_UNQ_ID = SOURCE_SYSTEM_ID || '_' || SOURCE_SYSTEM_CUSTID;
            COMMIT;

           -- Update SOLEPROP_F to 'INDIVIDUAL' when ENTITY_TYPE='C' and PATN 4th letter is 'P'
           -- UPDATE PSX_CUSTOMER_DATA_INCREMENTAL SET SOLEPROP_F  = 'INDIVIDUAL' ;
         --  COMMIT;
         --  UPDATE PSX_CUSTOMER_DATA_INCREMENTAL SET SOLEPROP_F  = 'CORPORATE' 
         --  WHERE ENTITY_TYPE = 'C' AND PAN IS NOT NULL AND SUBSTR(PAN, 4, 1) != 'P' OR SUBSTR(PAN, 4, 1) != 'H';

          -- Update SOLEPROP_F to 'INDIVIDUAL' when ENTITY_TYPE='CORPORATE' and PAN 4th letter is 'P' or 'H'
                        -- Update SOLEPROP_F to 'INDIVIDUAL' when ENTITY_TYPE='CORPORATE' and PAN 4th letter is 'P' or 'H'
            UPDATE /*+ enable_parallel_dml parallel(6) */ PSX_CUSTOMER_DATA_INCREMENTAL SET SOLEPROP_F  = 'INDIVIDUAL' 
            WHERE ENTITY_TYPE = 'CORPORATE' AND PAN IS NOT NULL AND SUBSTR(PAN, 4, 1) = 'P' OR SUBSTR(PAN, 4, 1) = 'H';

--            UPDATE PSX_CUSTOMER_DATA_INCREMENTAL SET CORPORATE_F  = 'CORPORATE' 
--            WHERE ENTITY_TYPE = 'CORPORATE' ;
COMMIT;
            UPDATE /*+ enable_parallel_dml parallel(6) */ PSX_CUSTOMER_DATA_INCREMENTAL 
            SET CORPORATE_F = CASE WHEN ENTITY_TYPE = 'CORPORATE' THEN 'CORPORATE' 
            WHEN ENTITY_TYPE = 'INDIVIDUAL' THEN NULL 
            ELSE CORPORATE_F END;

           COMMIT;


        EXCEPTION
            WHEN OTHERS THEN
                -- Updating EOD_STATUS "E" in PSX_EOD_CONTROL_T table in case of Exception
                UPDATE /*+ enable_parallel_dml parallel(6) */ PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T SET EOD_STATUS = 'E', ERROR_DESCRIPTION='PSX_CUSTOMER_EOD_DATA_PULL Procedure Execution Failed'
                WHERE BATCH_ID = v_batch_id AND EOD_STATUS='U' AND DATA_CATEGORY='CUSTOMER';
                COMMIT;
                -- Set output status to 'E' in case of error
                o_status := 'E';
                 p_descripition := 'Error in the PSX_CUSTOMER_EOD_DATA_PULL PROCEDURE';
                 p_sqlerror := 'Error: ' || SQLERRM || ' at ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;
               -- RAISE_APPLICATION_ERROR(-20001, 'Error occurred in the PSX_CUSTOMER_EOD_DATA_PULL procedure: ' || SQLERRM || ' at ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
        END;
    END IF;
END PSX_CUSTOMER_EOD_DATA_PULL;

===================================================================================================================

4. PSX_DATA_PULLING_TO_STAGING

create or replace PROCEDURE PSX_DATA_PULLING_TO_STAGING (
    v_batch_id IN VARCHAR2,
    v_psx_batch_id IN VARCHAR2,
    v_status OUT VARCHAR2,
    p_descripition out varchar2, -- descripition
    p_sqlerror out varchar2 -- sql error
) AS
BEGIN
    BEGIN
        -- Step 1: Insert duplicate records into the error table
         INSERT INTO /*+ APPEND */ PSX_CUSTOMER_DATA_INCREMENTAL_ERROR (CUST_UNQ_ID, INSERT_TS, SOURCE_SYSTEM, SOURCE_SYSTEM_CUSTID, BATCH_ID, PSX_BATCH_ID)
        SELECT /*+ enable_parallel_dml parallel(6) */ t.CUST_UNQ_ID, t.INSERT_TS, t.SOURCE_SYSTEM, t.SOURCE_SYSTEM_CUSTID, t.BATCH_ID, t.PSX_BATCH_ID
        FROM PSX_CUSTOMER_DATA_INCREMENTAL t
        WHERE t.CUST_UNQ_ID IN (
            SELECT CUST_UNQ_ID
            FROM PSX_CUSTOMER_DATA_INCREMENTAL
            GROUP BY CUST_UNQ_ID
            HAVING COUNT(*) > 1
        );

        COMMIT;

        -- Step 2: Insert latest unique records into the staging table
        INSERT /*+ APPEND */ INTO MASTER_PSX_CUS_BLK_STG (
            CUST_UNQ_ID,SOURCE_SYSTEM,SOLEPROP_F,CORPORATE_F, SOURCE_SYSTEM_CUSTID, BATCH_ID, PSX_BATCH_ID, CUST_IC, CREATED_FOR, BANK_UCIC, 
        CUST_CREATE_DATE, CUST_FIRST_NAME, CUST_MIDDLE_NAME, CUST_LAST_NAME, CUST_FULL_NAME, NAM_CUST_SHRT, 
        NAME_SALUTATION, GENDER, DOBDOI, MOTHER_NAME, FATHER_NAME, SPOUSE_NAME, EMPLOYER_NAME, PAN, PASSPORT, 
        VOTERID, DRIVING_LICENSE_NUMBER, NREGA, TAN, TIN, UDYAM_AADHAR_NO, CKYC, DIN, CIN, GSTIN_1, GSTIN_2, 
        GSTIN_3, GSTIN_4, GSTIN_5, GSTIN_6, GSTIN_7, GSTIN_8, GSTIN_9, GSTIN_10, IEC_NO, LEI, ADDRESS_TYPE_1, 
        ADDRESS_TYPE_2, ADDRESS_TYPE_3, ADDRESS_TYPE_4, ADDRESS_1, ADDRESS_2, ADDRESS_3, ADDRESS_4, CITY_1, CITY_2, 
        CITY_3, CITY_4, STATE_1, STATE_2, STATE_3, STATE_4, COUNTRY_1, COUNTRY_2, COUNTRY_3, COUNTRY_4, PINCODE_1, 
        PINCODE_2, PINCODE_3, PINCODE_4, EMAIL_TYPE_1, EMAIL_TYPE_2, EMAIL_1, EMAIL_2, PHONE_TYPE_1, PHONE_TYPE_2, 
        PHONE_TYPE_3, PHONE_1, PHONE_2, PHONE_3, AADHAR_NO, AADHAR_LINKED_STATUS, PASSPORT_DATEOFEXPIRY, 
        DRIVING_LICENSE_DATEOFEXPIRY, NREGA_DATEOFEXPIRY, OVD_STATUS, SHOP_ESTABLISHMENT, HOME_BRANCH_CODE, 
        HOME_BRANCH_DESCRIPTION, FATCA_FLAG, CUSTOMER_TYPE_CODE, CUSTOMER_TYPE_NAME, CUSTOMER_STATUS, CUSTOMER_SEGMENT, 
        CUSTOMER_CATEGORY, ENTITY_TYPE, APPLICANT_TYPE, PEP, GROUPID, KYC_STATUS, DATE_OF_KYCDONE, REKYC_DUEON, 
        RISK_CATEGORY, STAFF_EMPLOYEEID, STAFF_FLAG, YESFIRSTFLG, MINOR_FLAG, NATIONALITY, CONSTITUTION_TYPE, 
        AADHAR_DETAILS, KYC_MODE, EXTRA_NAME1, EXTRA_NAME2,EXTRA_NAME3, EXTRA_DATE1, EXTRA_DATE2,EXTRA_DATE3, EXTRA_EQUALITY1, EXTRA_EQUALITY2, 
        EXTRA_EQUALITY3, EXTRA_EQUALITY4, EXTRA_EQUALITY5, EXTRA_EQUALITY6, EXTRA_EQUALITY7, EXTRA_EQUALITY8, 
        EXTRA_EQUALITY9, EXTRA_EQUALITY10, ORIGINATING_PRODUCT, ORIGINATING_CHANNEL, ORIGINATING_STATUS, 
        ORIGINATING_REMARKS, ORIGINATING_LAST_UPDT, ORIGINATING_REJECTED_BY, 
            EVENTTYPE, 
            DUIFLAG, 
            INSERT_TIME, 
            LCHGTIME
        )
           SELECT /*+ enable_parallel_dml parallel(6) */ 
            CUST_UNQ_ID,SOURCE_SYSTEM,SOLEPROP_F,CORPORATE_F, SOURCE_SYSTEM_CUSTID, BATCH_ID, PSX_BATCH_ID, CUST_IC, CREATED_FOR, BANK_UCIC, 
        CUST_CREATE_DATE, CUST_FIRST_NAME, CUST_MIDDLE_NAME, CUST_LAST_NAME, CUST_FULL_NAME, NAM_CUST_SHRT, 
        NAME_SALUTATION, GENDER, DOBDOI, MOTHER_NAME, FATHER_NAME, SPOUSE_NAME, EMPLOYER_NAME, PAN, PASSPORT, 
        VOTERID, DRIVING_LICENSE_NUMBER, NREGA, TAN, TIN, UDYAM_AADHAR_NO, CKYC, DIN, CIN, GSTIN_1, GSTIN_2, 
        GSTIN_3, GSTIN_4, GSTIN_5, GSTIN_6, GSTIN_7, GSTIN_8, GSTIN_9, GSTIN_10, IEC_NO, LEI, ADDRESS_TYPE_1, 
        ADDRESS_TYPE_2, ADDRESS_TYPE_3, ADDRESS_TYPE_4, ADDRESS_1, ADDRESS_2, ADDRESS_3, ADDRESS_4, CITY_1, CITY_2, 
        CITY_3, CITY_4, STATE_1, STATE_2, STATE_3, STATE_4, COUNTRY_1, COUNTRY_2, COUNTRY_3, COUNTRY_4, PINCODE_1, 
        PINCODE_2, PINCODE_3, PINCODE_4, EMAIL_TYPE_1, EMAIL_TYPE_2, EMAIL_1, EMAIL_2, PHONE_TYPE_1, PHONE_TYPE_2, 
        PHONE_TYPE_3, PHONE_1, PHONE_2, PHONE_3, AADHAR_NO, AADHAR_LINKED_STATUS, PASSPORT_DATEOFEXPIRY, 
        DRIVING_LICENSE_DATEOFEXPIRY, NREGA_DATEOFEXPIRY, OVD_STATUS, SHOP_ESTABLISHMENT, HOME_BRANCH_CODE, 
        HOME_BRANCH_DESCRIPTION, FATCA_FLAG, CUSTOMER_TYPE_CODE, CUSTOMER_TYPE_NAME, CUSTOMER_STATUS, CUSTOMER_SEGMENT, 
        CUSTOMER_CATEGORY, ENTITY_TYPE, APPLICANT_TYPE, PEP, GROUPID, KYC_STATUS, DATE_OF_KYCDONE, REKYC_DUEON, 
        RISK_CATEGORY, STAFF_EMPLOYEEID, STAFF_FLAG, YESFIRSTFLG, MINOR_FLAG, NATIONALITY, CONSTITUTION_TYPE, 
        AADHAR_DETAILS, KYC_MODE, EXTRA_NAME1, EXTRA_NAME2,EXTRA_NAME3, EXTRA_DATE1, EXTRA_DATE2,EXTRA_DATE3, EXTRA_EQUALITY1, EXTRA_EQUALITY2, 
        EXTRA_EQUALITY3, EXTRA_EQUALITY4, EXTRA_EQUALITY5, EXTRA_EQUALITY6, EXTRA_EQUALITY7, EXTRA_EQUALITY8, 
        EXTRA_EQUALITY9, EXTRA_EQUALITY10, ORIGINATING_PRODUCT, ORIGINATING_CHANNEL, ORIGINATING_STATUS, 
        ORIGINATING_REMARKS, ORIGINATING_LAST_UPDT, ORIGINATING_REJECTED_BY, 
            'INCREMENTAL' AS EVENTTYPE, 
            'I_OR_U' AS DUIFLAG, 
            INSERT_TS AS INSERT_TIME, 
            INSERT_TS AS LCHGTIME
        FROM (
            WITH RankedRecords AS (
                SELECT /*+ enable_parallel_dml parallel(6) */
                    t.CUST_UNQ_ID,t.SOURCE_SYSTEM,t.SOLEPROP_F,t.CORPORATE_F, t.SOURCE_SYSTEM_CUSTID, t.BATCH_ID, t.PSX_BATCH_ID, t.CUST_IC, t.CREATED_FOR, t.BANK_UCIC, 
        t.CUST_CREATE_DATE, t.CUST_FIRST_NAME, t.CUST_MIDDLE_NAME, t.CUST_LAST_NAME, t.CUST_FULL_NAME, t.NAM_CUST_SHRT, 
        t.NAME_SALUTATION, t.GENDER, t.DOBDOI, t.MOTHER_NAME, t.FATHER_NAME, t.SPOUSE_NAME, t.EMPLOYER_NAME, t.PAN, t.PASSPORT, 
        t.VOTERID, t.DRIVING_LICENSE_NUMBER, t.NREGA, t.TAN, t.TIN, t.UDYAM_AADHAR_NO, t.CKYC, t.DIN, t.CIN, t.GSTIN_1, t.GSTIN_2, 
        t.GSTIN_3, t.GSTIN_4, t.GSTIN_5, t.GSTIN_6, t.GSTIN_7, t.GSTIN_8, t.GSTIN_9, t.GSTIN_10, t.IEC_NO, t.LEI, t.ADDRESS_TYPE_1, 
        t.ADDRESS_TYPE_2, t.ADDRESS_TYPE_3, t.ADDRESS_TYPE_4, t.ADDRESS_1, t.ADDRESS_2, t.ADDRESS_3, t.ADDRESS_4, t.CITY_1, t.CITY_2, 
        t.CITY_3, t.CITY_4, t.STATE_1, t.STATE_2, t.STATE_3, t.STATE_4, t.COUNTRY_1, t.COUNTRY_2, t.COUNTRY_3, t.COUNTRY_4, t.PINCODE_1, 
        t.PINCODE_2, t.PINCODE_3, t.PINCODE_4, t.EMAIL_TYPE_1, t.EMAIL_TYPE_2, t.EMAIL_1, t.EMAIL_2, t.PHONE_TYPE_1, t.PHONE_TYPE_2, 
        t.PHONE_TYPE_3, t.PHONE_1, t.PHONE_2, t.PHONE_3, t.AADHAR_NO, t.AADHAR_LINKED_STATUS, t.PASSPORT_DATEOFEXPIRY, 
        t.DRIVING_LICENSE_DATEOFEXPIRY, t.NREGA_DATEOFEXPIRY, t.OVD_STATUS, t.SHOP_ESTABLISHMENT, t.HOME_BRANCH_CODE, 
        t.HOME_BRANCH_DESCRIPTION, t.FATCA_FLAG, t.CUSTOMER_TYPE_CODE, t.CUSTOMER_TYPE_NAME, t.CUSTOMER_STATUS, t.CUSTOMER_SEGMENT, 
        t.CUSTOMER_CATEGORY, t.ENTITY_TYPE, t.APPLICANT_TYPE, t.PEP, t.GROUPID, t.KYC_STATUS, t.DATE_OF_KYCDONE, t.REKYC_DUEON, 
        t.RISK_CATEGORY, t.STAFF_EMPLOYEEID, t.STAFF_FLAG, t.YESFIRSTFLG, t.MINOR_FLAG, t.NATIONALITY, t.CONSTITUTION_TYPE, 
        t.AADHAR_DETAILS, t.KYC_MODE, t.EXTRA_NAME1, t.EXTRA_NAME2, t.EXTRA_NAME3, t.EXTRA_DATE1, t.EXTRA_DATE2, t.EXTRA_DATE3, t.EXTRA_EQUALITY1, t.EXTRA_EQUALITY2, 
        t.EXTRA_EQUALITY3, t.EXTRA_EQUALITY4, t.EXTRA_EQUALITY5, t.EXTRA_EQUALITY6, t.EXTRA_EQUALITY7, t.EXTRA_EQUALITY8, 
        t.EXTRA_EQUALITY9, t.EXTRA_EQUALITY10, t.ORIGINATING_PRODUCT, t.ORIGINATING_CHANNEL, t.ORIGINATING_STATUS, 
        t.ORIGINATING_REMARKS, t.ORIGINATING_LAST_UPDT, t.ORIGINATING_REJECTED_BY,
                    t.INSERT_TS,
                    ROW_NUMBER() OVER (
                        PARTITION BY t.CUST_UNQ_ID 
                        ORDER BY t.INSERT_TS DESC
                    ) AS rn
                FROM PSX_CUSTOMER_DATA_INCREMENTAL t
            )
            SELECT /*+ enable_parallel_dml parallel(6) */
                CUST_UNQ_ID,SOURCE_SYSTEM,SOLEPROP_F,CORPORATE_F, SOURCE_SYSTEM_CUSTID, BATCH_ID, PSX_BATCH_ID, CUST_IC, CREATED_FOR, BANK_UCIC, 
        CUST_CREATE_DATE, CUST_FIRST_NAME, CUST_MIDDLE_NAME, CUST_LAST_NAME, CUST_FULL_NAME, NAM_CUST_SHRT, 
        NAME_SALUTATION, GENDER, DOBDOI, MOTHER_NAME, FATHER_NAME, SPOUSE_NAME, EMPLOYER_NAME, PAN, PASSPORT, 
        VOTERID, DRIVING_LICENSE_NUMBER, NREGA, TAN, TIN, UDYAM_AADHAR_NO, CKYC, DIN, CIN, GSTIN_1, GSTIN_2, 
        GSTIN_3, GSTIN_4, GSTIN_5, GSTIN_6, GSTIN_7, GSTIN_8, GSTIN_9, GSTIN_10, IEC_NO, LEI, ADDRESS_TYPE_1, 
        ADDRESS_TYPE_2, ADDRESS_TYPE_3, ADDRESS_TYPE_4, ADDRESS_1, ADDRESS_2, ADDRESS_3, ADDRESS_4, CITY_1, CITY_2, 
        CITY_3, CITY_4, STATE_1, STATE_2, STATE_3, STATE_4, COUNTRY_1, COUNTRY_2, COUNTRY_3, COUNTRY_4, PINCODE_1, 
        PINCODE_2, PINCODE_3, PINCODE_4, EMAIL_TYPE_1, EMAIL_TYPE_2, EMAIL_1, EMAIL_2, PHONE_TYPE_1, PHONE_TYPE_2, 
        PHONE_TYPE_3, PHONE_1, PHONE_2, PHONE_3, AADHAR_NO, AADHAR_LINKED_STATUS, PASSPORT_DATEOFEXPIRY, 
        DRIVING_LICENSE_DATEOFEXPIRY, NREGA_DATEOFEXPIRY, OVD_STATUS, SHOP_ESTABLISHMENT, HOME_BRANCH_CODE, 
        HOME_BRANCH_DESCRIPTION, FATCA_FLAG, CUSTOMER_TYPE_CODE, CUSTOMER_TYPE_NAME, CUSTOMER_STATUS, CUSTOMER_SEGMENT, 
        CUSTOMER_CATEGORY, ENTITY_TYPE, APPLICANT_TYPE, PEP, GROUPID, KYC_STATUS, DATE_OF_KYCDONE, REKYC_DUEON, 
        RISK_CATEGORY, STAFF_EMPLOYEEID, STAFF_FLAG, YESFIRSTFLG, MINOR_FLAG, NATIONALITY, CONSTITUTION_TYPE, 
        AADHAR_DETAILS, KYC_MODE, EXTRA_NAME1, EXTRA_NAME2,EXTRA_NAME3, EXTRA_DATE1, EXTRA_DATE2,EXTRA_DATE3, EXTRA_EQUALITY1, EXTRA_EQUALITY2, 
        EXTRA_EQUALITY3, EXTRA_EQUALITY4, EXTRA_EQUALITY5, EXTRA_EQUALITY6, EXTRA_EQUALITY7, EXTRA_EQUALITY8, 
        EXTRA_EQUALITY9, EXTRA_EQUALITY10, ORIGINATING_PRODUCT, ORIGINATING_CHANNEL, ORIGINATING_STATUS, 
        ORIGINATING_REMARKS, ORIGINATING_LAST_UPDT, ORIGINATING_REJECTED_BY, 
                INSERT_TS 
            FROM RankedRecords
            WHERE rn = 1
        );

        COMMIT;

 INSERT /*+ APPEND */ INTO PSXIDS_DT_2_HASHING (
    CUST_UNQ_ID,
    BATCH_ID,
    PSX_BATCH_ID,
    DUI_FLAG
)
SELECT /*+ PARALLEL(stg, 1) */
    stg.CUST_UNQ_ID,
    stg.BATCH_ID,
    stg.PSX_BATCH_ID,
    CASE 
        WHEN trg.CUST_UNQ_ID IS NOT NULL THEN 'CO'  -- 'CO' if the CUST_UNQ_ID exists in P0_PSX_CUS_BLK_TRG
        ELSE 'I'  -- 'I' if the CUST_UNQ_ID does not exist in P0_PSX_CUS_BLK_TRG
    END AS DUI_FLAG
FROM 
    MASTER_PSX_CUS_BLK_STG stg
LEFT JOIN 
    P0_PSX_CUS_BLK_TRG trg
ON 
    stg.CUST_UNQ_ID = trg.CUST_UNQ_ID;

COMMIT;

        -- In case of any success, setting status to 'C'
        v_status := 'C';

    EXCEPTION
        -- In case of any error, set status to 'E'
        WHEN OTHERS THEN
         -- Updating EOD_STATUS "E" in PSX_EOD_CONTROL_T table in case of Exception
                UPDATE /*+ PARALLEL(1) */ PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T SET EOD_STATUS = 'E', ERROR_DESCRIPTION='PSX_DATA_PULLING_TO_STAGING Procedure Execution Failed'
                WHERE BATCH_ID = v_batch_id AND EOD_STATUS='U' AND DATA_CATEGORY='CUSTOMER';
                COMMIT;
            v_status := 'E';
            p_descripition := 'Error in the PSX_DATA_PULLING_TO_STAGING PROCEDURE';
            p_sqlerror := 'Error: ' || SQLERRM || ' at ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;
            --RAISE_APPLICATION_ERROR(-20001, 'Error occurred in the PSX_DATA_PULLING_TO_STAGING procedure: ' || SQLERRM || ' at ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    END;
END PSX_DATA_PULLING_TO_STAGING;

==================================================================================================================

5. PSX_DATA_PULLING_FROM_CLIP_TO_PRIME360

create or replace PROCEDURE PSX_DATA_PULLING_FROM_CLIP_TO_PRIME360 (
    v_batch_id VARCHAR2,         -- Input parameter for BATCH_ID
    v_psx_batch_id IN VARCHAR2,  -- Input parameter for PSX_BATCH_ID
    o_status OUT VARCHAR2,       -- Output parameter for status
    p_descripition out varchar2, -- descripition
    p_sqlerror out varchar2 -- sql error
    
) 
IS
    agent sys.aq$_agent := sys.aq$_agent(' ', NULL, 0);
    MESSAGE sys.aq$_jms_message;
    enqueue_options dbms_aq.enqueue_options_t;
    message_properties dbms_aq.message_properties_t;
    msgid raw(16);
    json_payload       VARCHAR2(4000); -- JSON payload

BEGIN

     -- Construct the JSON payload
    json_payload := '{"PSX_BATCH_ID":"' || v_psx_batch_id || '"}';

    -- Inserting data from MASTER_PSX_CUS_BLK_STG to PRIME360_CUS_STG based on PSX_BATCH_ID
    INSERT /*+ APPEND */ INTO PROD_PRIME360DEDUPE.PRIME360_CUS_STG (
    CUST_UNQ_ID, SOURCE_SYSTEM_CUSTID, SOLEPROP_F,CORPORATE_F, CUST_IC, BATCH_ID, CLIENT_REQUESTID, FEED_SYS_ID, SOURCE_SYS_ID, REQUEST_TYPE, 
    SOURCE_SYSTEM, REQUESTED_BY, UNIQUEID, PSX_BATCH_ID, OLD_PSX_BATCH_ID, LCHGTIME, DUIFLAG, EVENTTYPE, 
    INSERT_TIME, PARTITION_NUMBER, NSPKEY, RECORD_ID, ICCLEANING_SPECTRUM, CREATED_FOR, BANK_UCIC, CUST_CREATE_DATE, 
    CUST_FIRST_NAME, CUST_MIDDLE_NAME, CUST_LAST_NAME, CUST_FULL_NAME, NAM_CUST_SHRT, NAME_SALUTATION, GENDER, 
    DOBDOI, MOTHER_NAME, FATHER_NAME, SPOUSE_NAME, EMPLOYER_NAME, UCIC, PAN, PASSPORT, VOTERID, DRIVING_LICENSE_NUMBER, 
    NREGA, TAN, TIN, UDYAM_AADHAR_NO, CKYC, DIN, CIN, GSTIN_1, GSTIN_2, GSTIN_3, GSTIN_4, GSTIN_5, GSTIN_6, GSTIN_7, 
    GSTIN_8, GSTIN_9, GSTIN_10, IEC_NO, LEI, AADHAR_NO, AADHAR_LINKED_STATUS, PASSPORT_DATEOFEXPIRY, 
    DRIVING_LICENSE_DATEOFEXPIRY, NREGA_DATEOFEXPIRY, OVD_STATUS, SHOP_ESTABLISHMENT, HOME_BRANCH_CODE, 
    HOME_BRANCH_DESCRIPTION, FATCA_FLAG, CUSTOMER_TYPE_CODE, CUSTOMER_TYPE_NAME, CUSTOMER_STATUS, CUSTOMER_SEGMENT, 
    CUSTOMER_CATEGORY, ENTITY_TYPE, APPLICANT_TYPE, PEP, GROUPID, KYC_STATUS, DATE_OF_KYCDONE, REKYC_DUEON, 
    RISK_CATEGORY, STAFF_EMPLOYEEID, STAFF_FLAG, YESFIRSTFLG, MINOR_FLAG, NATIONALITY, CONSTITUTION_TYPE, AADHAR_DETAILS, 
    KYC_MODE, EXTRA_NAME1, EXTRA_NAME2,EXTRA_NAME3, EXTRA_DATE1, EXTRA_DATE2,EXTRA_DATE3, EXTRA_EQUALITY1, EXTRA_EQUALITY2, EXTRA_EQUALITY3, 
    EXTRA_EQUALITY4, EXTRA_EQUALITY5, EXTRA_EQUALITY6, EXTRA_EQUALITY7, EXTRA_EQUALITY8, EXTRA_EQUALITY9, 
    EXTRA_EQUALITY10, ORIGINATING_PRODUCT, ORIGINATING_CHANNEL, ORIGINATING_STATUS, 
    ORIGINATING_REMARKS, ORIGINATING_LAST_UPDT, ORIGINATING_REJECTED_BY, 
    ADDRESS_TYPE_1, ADDRESS_TYPE_2, ADDRESS_TYPE_3, ADDRESS_TYPE_4, ADDRESS_1, ADDRESS_2, ADDRESS_3, ADDRESS_4, 
    CITY_1, CITY_2, CITY_3, CITY_4, STATE_1, STATE_2, STATE_3, STATE_4, COUNTRY_1, COUNTRY_2, COUNTRY_3, COUNTRY_4, 
    PINCODE_1, PINCODE_2, PINCODE_3, PINCODE_4, EMAIL_TYPE_1, EMAIL_TYPE_2, EMAIL_1, EMAIL_2, PHONE_TYPE_1, 
    PHONE_TYPE_2, PHONE_TYPE_3, PHONE_1, PHONE_2, PHONE_3, ADJACENCYLIST, ISPARTIAL, CLUSTERING_0, CLUSTERING_CNT_0, 
    EQUATION_0, CLUSTERING_1, CLUSTERING_CNT_1, EQUATION_1, CLUSTERING_2, CLUSTERING_CNT_2, EQUATION_2, CLUSTERING_3, 
    CLUSTERING_CNT_3, EQUATION_3,SOURCE_SYSTEM_DATE
)
SELECT /*+ enable_parallel_dml parallel(MASTER_PSX_CUS_BLK_STG, 6) */ CUST_UNQ_ID, SOURCE_SYSTEM_CUSTID, SOLEPROP_F,CORPORATE_F, CUST_IC, BATCH_ID, CLIENT_REQUESTID, FEED_SYS_ID, SOURCE_SYS_ID, REQUEST_TYPE, 
    SOURCE_SYSTEM, REQUESTED_BY, UNIQUEID, PSX_BATCH_ID, OLD_PSX_BATCH_ID, LCHGTIME, DUIFLAG, EVENTTYPE, 
    INSERT_TIME, PARTITION_NUMBER, NSPKEY, RECORD_ID, ICCLEANING_SPECTRUM, CREATED_FOR, BANK_UCIC, CUST_CREATE_DATE, 
    CUST_FIRST_NAME, CUST_MIDDLE_NAME, CUST_LAST_NAME, CUST_FULL_NAME, NAM_CUST_SHRT, NAME_SALUTATION, GENDER, 
    DOBDOI, MOTHER_NAME, FATHER_NAME, SPOUSE_NAME, EMPLOYER_NAME, UCIC, PAN, PASSPORT, VOTERID, DRIVING_LICENSE_NUMBER, 
    NREGA, TAN, TIN, UDYAM_AADHAR_NO, CKYC, DIN, CIN, GSTIN_1, GSTIN_2, GSTIN_3, GSTIN_4, GSTIN_5, GSTIN_6, GSTIN_7, 
    GSTIN_8, GSTIN_9, GSTIN_10, IEC_NO, LEI, AADHAR_NO, AADHAR_LINKED_STATUS, PASSPORT_DATEOFEXPIRY, 
    DRIVING_LICENSE_DATEOFEXPIRY, NREGA_DATEOFEXPIRY, OVD_STATUS, SHOP_ESTABLISHMENT, HOME_BRANCH_CODE, 
    HOME_BRANCH_DESCRIPTION, FATCA_FLAG, CUSTOMER_TYPE_CODE, CUSTOMER_TYPE_NAME, CUSTOMER_STATUS, CUSTOMER_SEGMENT, 
    CUSTOMER_CATEGORY, ENTITY_TYPE, APPLICANT_TYPE, PEP, GROUPID, KYC_STATUS, DATE_OF_KYCDONE, REKYC_DUEON, 
    RISK_CATEGORY, STAFF_EMPLOYEEID, STAFF_FLAG, YESFIRSTFLG, MINOR_FLAG, NATIONALITY, CONSTITUTION_TYPE, AADHAR_DETAILS, 
    KYC_MODE, EXTRA_NAME1, EXTRA_NAME2,EXTRA_NAME3, EXTRA_DATE1, EXTRA_DATE2,EXTRA_DATE3, EXTRA_EQUALITY1, EXTRA_EQUALITY2, EXTRA_EQUALITY3, 
    EXTRA_EQUALITY4, EXTRA_EQUALITY5, EXTRA_EQUALITY6, EXTRA_EQUALITY7, EXTRA_EQUALITY8, EXTRA_EQUALITY9, 
    EXTRA_EQUALITY10, ORIGINATING_PRODUCT, ORIGINATING_CHANNEL, ORIGINATING_STATUS, 
    ORIGINATING_REMARKS, ORIGINATING_LAST_UPDT, ORIGINATING_REJECTED_BY, 
    ADDRESS_TYPE_1, ADDRESS_TYPE_2, ADDRESS_TYPE_3, ADDRESS_TYPE_4, ADDRESS_1, ADDRESS_2, ADDRESS_3, ADDRESS_4, 
    CITY_1, CITY_2, CITY_3, CITY_4, STATE_1, STATE_2, STATE_3, STATE_4, COUNTRY_1, COUNTRY_2, COUNTRY_3, COUNTRY_4, 
    PINCODE_1, PINCODE_2, PINCODE_3, PINCODE_4, EMAIL_TYPE_1, EMAIL_TYPE_2, EMAIL_1, EMAIL_2, PHONE_TYPE_1, 
    PHONE_TYPE_2, PHONE_TYPE_3, PHONE_1, PHONE_2, PHONE_3, ADJACENCYLIST, ISPARTIAL, CLUSTERING_0, CLUSTERING_CNT_0, 
    EQUATION_0, CLUSTERING_1, CLUSTERING_CNT_1, EQUATION_1, CLUSTERING_2, CLUSTERING_CNT_2, EQUATION_2, CLUSTERING_3, 
    CLUSTERING_CNT_3, EQUATION_3,SOURCE_SYSTEM_DATE
FROM MASTER_PSX_CUS_BLK_STG
WHERE PSX_BATCH_ID = v_psx_batch_id;


    COMMIT;

    -- Purging the PSX_EOD_QUEUE_TBL
    DELETE FROM PROD_PRIME360DEDUPE.PSX_EOD_QUEUE_TBL;

    COMMIT;




    -- Enqueue PSX_EOD_QUEUE
    MESSAGE := sys.aq$_jms_message.construct(dbms_aq.JMS_TEXT_MESSAGE);
    message.set_replyto(agent);
    message.set_type('tkaqpet2');
    message.set_userid('yesbnk');
    message.set_appid('plsql_enq');
    message.set_groupid('st');
    message.set_groupseq(1);
    message.set_Short_Property('systemId',1);
    message.set_Long_Property('psxIdBatchId',v_psx_batch_id);  -- Use the input batch ID
    message.set_Short_Property('purposeId',99);
    message.set_string_property('PSX_BATCH_ID', v_psx_batch_id); 
    message.set_text(json_payload);


    DBMS_AQ.ENQUEUE(
        queue_name => 'PROD_PRIME360DEDUPE.PSX_EOD_QUEUE',
        enqueue_options => enqueue_options,
        message_properties => message_properties,
        payload => message,
        msgid => msgid
    );

    -- Setting status as 'C' for success
    o_status := 'C';

    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        -- Updating STATUS "E" in PSX_EOD_CONTROL_T table in case of Exception
                UPDATE /*+ PARALLEL(1) */ PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T SET EOD_STATUS = 'E', ERROR_DESCRIPTION='PSX_DATA_PULLING_FROM_CLIP_TO_PRIME360 Procedure Execution Failed'
                WHERE BATCH_ID = v_batch_id AND EOD_STATUS='U' AND DATA_CATEGORY='CUSTOMER';
                COMMIT;
        -- Setting status as 'E' for error
        o_status := 'E';
         p_descripition := 'Error in the PSX_DATA_PULLING_FROM_CLIP_TO_PRIME360 PROCEDURE';
         p_sqlerror := 'Error: ' || SQLERRM || ' at ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;
         --RAISE_APPLICATION_ERROR(-20001, 'Error occurred in the PSX_DATA_PULLING_FROM_CLIP_TO_PRIME360 procedure: ' || SQLERRM || ' at ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
END PSX_DATA_PULLING_FROM_CLIP_TO_PRIME360;

====================================================================================================================

6. PSX_CLIP_SUCCESS_POST_DMLS

create or replace PROCEDURE PSX_CLIP_SUCCESS_POST_DMLS (
    v_psx_batch_id  IN VARCHAR2,
    v_batch_id      IN VARCHAR2,
    o_status        OUT VARCHAR2,   -- Output Parameter for Status
    p_descripition out varchar2, -- descripition
    p_sqlerror out varchar2 -- sql error
)
AS
    v_count NUMBER;
    control_t_success_count NUMBER;
    control_t_failure_count NUMBER;
    psx_incr_count NUMBER;
    psx_stg_count NUMBER;
    psx_p0_trg_count NUMBER;
    psx_crt_count NUMBER;
    client_batch_id NUMBER;
    psx_p0_trg_total_count NUMBER;
    psx_crt_total_count NUMBER;
    total_obj_count NUMBER;


BEGIN

 -- Inserting into PSX_UCIC table which is in staging schema
    INSERT /*+ APPEND */ INTO PROD_PSX_DEDUPE_STAGING.PSX_UCIC (CUST_UNQ_ID, UCIC, PSX_BATCH_ID, BATCH_ID, INSERT_TS, SOURCE_SYSTEM_NAME, SOURCE_SYSTEM_CUSTID)
    SELECT /*+ PARALLEL(CRT, 1) PARALLEL(TRG, 1) */ 
        CRT.CUST_UNQ_ID,               
        CRT.MPC,     
        CRT.PSX_BATCH_ID,         
        CRT.BATCH_ID,
        CRT.INSERT_TS,
        TRG.SOURCE_SYSTEM,             
        TRG.SOURCE_SYSTEM_CUSTID            
    FROM 
        PSX_CLUSTER_CROSS_REF_T CRT
    JOIN 
        P0_PSX_CUS_BLK_TRG TRG 
    ON 
        CRT.CUST_UNQ_ID = TRG.CUST_UNQ_ID
    WHERE 
        CRT.PSX_BATCH_ID = v_psx_batch_id;  

COMMIT;

-- Updating the CLIP CRT table MPC in PRIME P0_PSX_CUS_BLK_TRG table POSIDEX_UCIC column
MERGE /*+ enable_parallel_dml parallel(6) */ INTO PROD_PRIME360DEDUPE.P0_PSX_CUS_BLK_TRG prime_trg
USING (
    SELECT clip_crt.cust_unq_id, clip_crt.mpc
    FROM PSX_CLUSTER_CROSS_REF_T clip_crt
    WHERE clip_crt.psx_batch_id = v_psx_batch_id
) src
ON (prime_trg.cust_unq_id = src.cust_unq_id)
WHEN MATCHED THEN
    UPDATE SET prime_trg.posidex_ucic = src.mpc;

COMMIT;

-- Updating the CLIP CRT table MPC in PRIME CRT table UCIC column
MERGE /*+ enable_parallel_dml parallel(6) */ INTO PROD_PRIME360DEDUPE.PSX_CLUSTER_CROSS_REF_T prime_crt
USING (
    SELECT clip_crt.cust_unq_id, clip_crt.mpc
    FROM PSX_CLUSTER_CROSS_REF_T clip_crt
    WHERE clip_crt.psx_batch_id = v_psx_batch_id
) src
ON (prime_crt.cust_unq_id = src.cust_unq_id)
WHEN MATCHED THEN
    UPDATE SET prime_crt.ucic = src.mpc;

COMMIT;

    -- Getting the count from P0_PSX_CUS_BLK_TRG
  --  SELECT  COUNT(*) INTO v_count 
 --   FROM P0_PSX_CUS_BLK_TRG 
  --  WHERE PSX_BATCH_ID = v_psx_batch_id;

    -- Updating EOD_STATUS and PSX_COUNT columns in PSX_EOD_CONTROL_T 
  --  UPDATE /*+ PARALLEL(1) */  PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T
 --   SET EOD_STATUS = 'C', PSX_COUNT = v_count
  --  WHERE PSX_BATCH_ID = v_psx_batch_id and EOD_STATUS='U';

  UPDATE /*+ enable_parallel_dml parallel(6) */ PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T ec
    SET ec.EOD_STATUS='C', ec.PSX_COUNT = (
        SELECT COUNT(*)
        FROM P0_PSX_CUS_BLK_TRG trg
        WHERE trg.PSX_BATCH_ID = v_psx_batch_id
          AND trg.SOURCE_SYSTEM = ec.SOURCE_SYSTEM
    )
    WHERE ec.PSX_BATCH_ID = v_psx_batch_id
      AND ec.DATA_CATEGORY = 'CUSTOMER'
      AND ec.EOD_STATUS in ('U','E');

    COMMIT;

-- Getting BATCH_ID from PSX_EOD_CONTROL_T based on PSX_BATCH_ID
    SELECT DISTINCT BATCH_ID 
    INTO client_batch_id 
    FROM PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T 
    WHERE PSX_BATCH_ID = v_psx_batch_id;

    -- Getting the EOD_STATUS "C" count from PSX_EOD_CONTROL_T based on PSX_BATCH_ID
    SELECT SUM(BATCH_TOTAL_REC_COUNT)
    INTO control_t_success_count
    FROM PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T
    WHERE EOD_STATUS='C' AND PSX_BATCH_ID = v_psx_batch_id;


    -- Getting the EOD_STATUS "E" count from PSX_EOD_CONTROL_T based on PSX_BATCH_ID
    SELECT SUM(BATCH_TOTAL_REC_COUNT)
    INTO control_t_failure_count
    FROM PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T
    WHERE EOD_STATUS='E' AND PSX_BATCH_ID = v_psx_batch_id;


    -- Getting the count from PSX_CUSTOMER_DATA_INCREMENTAL based on PSX_BATCH_ID
    SELECT COUNT(*)
    INTO psx_incr_count 
    FROM PSX_CUSTOMER_DATA_INCREMENTAL
    WHERE PSX_BATCH_ID = v_psx_batch_id;


    -- Getting the count from MASTER_PSX_CUS_BLK_STG based on PSX_BATCH_ID
    SELECT COUNT(*)
    INTO psx_stg_count 
    FROM MASTER_PSX_CUS_BLK_STG
    WHERE PSX_BATCH_ID = v_psx_batch_id;


    -- Getting the count from P0_PSX_CUS_BLK_TRG based on PSX_BATCH_ID
    SELECT COUNT(*)
    INTO psx_p0_trg_count 
    FROM P0_PSX_CUS_BLK_TRG
    WHERE PSX_BATCH_ID = v_psx_batch_id;


    -- Getting the count from PSX_CLUSTER_CROSS_REF_T based on PSX_BATCH_ID
    SELECT COUNT(*)
    INTO psx_crt_count 
    FROM PSX_CLUSTER_CROSS_REF_T
    WHERE PSX_BATCH_ID = v_psx_batch_id;

    -- Getting the total records count from P0_PSX_CUS_BLK_TRG
    SELECT COUNT(*)
    INTO psx_p0_trg_total_count 
    FROM P0_PSX_CUS_BLK_TRG;

    -- Getting the total records count from PSX_CLUSTER_CROSS_REF_T
    SELECT COUNT(*)
    INTO psx_crt_total_count 
    FROM PSX_CLUSTER_CROSS_REF_T;

    -- Getting the total object count from PSX_OBJECT_STATS based on PSX_BATCH_ID
    SELECT CUSTOMER_P0
    INTO total_obj_count 
    FROM PSX_OBJECT_STATS
    WHERE PSX_BATCH_ID = v_psx_batch_id;

      -- Inserting all the counts in PSX_CLIP_EOD_DATA_COUNTS
    INSERT /*+ APPEND */ INTO PSX_CLIP_EOD_DATA_COUNTS(BATCH_ID,PSX_BATCH_ID,YBL_VALID_COUNT,YBL_INVALID_COUNT,PSX_INCR_COUNT,PSX_STG_COUNT,
    P0_TRG_COUNT,CRT_COUNT,OBJECT_TOTAL_COUNT,P0_TRG_TOTAL_COUNT,CRT_TOTAL_COUNT) VALUES(client_batch_id,v_psx_batch_id,control_t_success_count,control_t_failure_count,psx_incr_count,psx_stg_count,psx_p0_trg_count,
    psx_crt_count,total_obj_count,psx_p0_trg_total_count,psx_crt_total_count);	

    COMMIT;

    -- Auditing PSX_STRENGTH_FILTER table
    INSERT /*+ APPEND */  INTO PSX_STRENGTH_FILTER_ADT (RECORD_ID,MATCHED_RECORD_ID,EQUATION_0,EQUATION_1,EQUATION_2,EQUATION_3,PSX_BATCH_ID,LCHGTIME,PAN_STRENGTH,MATCHTYPE,AADHAR_STRENGTH,ADDRESS_STRENGTH,BANK_UCIC_STRENGTH,CIN_STRENGTH,CKYC_STRENGTH,CUST_FULL_NAME_STRENGTH,DIN_STRENGTH,DOBDOI_STRENGTH,DRIVING_LICENSE_STRENGTH,DISTRICT_CITY_STRENGTH,EMAIL_ID_STRENGTH,FATHER_NAME_STRENGTH,GSTIN_STRENGTH,IEC_NO_STRENGTH,LEI_STRENGTH,MOTHER_NAME_STRENGTH,NREGA_STRENGTH,PASSPORT_STRENGTH,PHONE_STRENGTH,PINCODE_STRENGTH,SHOP_ESTABLISHMENT_STRENGTH,SPOUSE_NAME_STRENGTH,TAN_STRENGTH,TIN_STRENGTH,UDYAM_AADHAR_NO_STRENGTH,VOTERID_STRENGTH)
    SELECT /*+ enable_parallel_dml parallel(PSX_STRENGTH_FILTER, 1) */ RECORD_ID,MATCHED_RECORD_ID,EQUATION_0,EQUATION_1,EQUATION_2,EQUATION_3,PSX_BATCH_ID,LCHGTIME,PAN_STRENGTH,MATCHTYPE,AADHAR_STRENGTH,ADDRESS_STRENGTH,BANK_UCIC_STRENGTH,CIN_STRENGTH,CKYC_STRENGTH,CUST_FULL_NAME_STRENGTH,DIN_STRENGTH,DOBDOI_STRENGTH,DRIVING_LICENSE_STRENGTH,DISTRICT_CITY_STRENGTH,EMAIL_ID_STRENGTH,FATHER_NAME_STRENGTH,GSTIN_STRENGTH,IEC_NO_STRENGTH,LEI_STRENGTH,MOTHER_NAME_STRENGTH,NREGA_STRENGTH,PASSPORT_STRENGTH,PHONE_STRENGTH,PINCODE_STRENGTH,SHOP_ESTABLISHMENT_STRENGTH,SPOUSE_NAME_STRENGTH,TAN_STRENGTH,TIN_STRENGTH,UDYAM_AADHAR_NO_STRENGTH,VOTERID_STRENGTH FROM PSX_STRENGTH_FILTER;
Commit;
    -- Truncating PSX_STRENGTH_FILTER table
    EXECUTE IMMEDIATE 'TRUNCATE TABLE PSX_STRENGTH_FILTER';

    COMMIT;

    -- Auditing YBL_CUSTOMER_DATA_INCREMENTAL table
    INSERT /*+ APPEND */ INTO PROD_PSX_DEDUPE_STAGING.YBL_CUSTOMER_DATA_INCREMENTAL_ADT (SOURCE_SYSTEM,SOURCE_SYSTEM_CUSTID,INSERT_TS,SOURCE_SYSTEM_DATE,BATCH_ID,CUST_IC,CREATED_FOR,BANK_UCIC,CUST_CREATE_DATE,CUST_FIRST_NAME,CUST_MIDDLE_NAME,CUST_LAST_NAME,CUST_FULL_NAME,NAM_CUST_SHRT,NAME_SALUTATION,GENDER,DOBDOI,MOTHER_NAME,FATHER_NAME,SPOUSE_NAME,EMPLOYER_NAME,PAN,PASSPORT,VOTERID,DRIVING_LICENSE_NUMBER,NREGA,TAN,TIN,UDYAM_AADHAR_NO,CKYC,DIN,CIN,GSTIN_1,GSTIN_2,GSTIN_3,GSTIN_4,GSTIN_5,GSTIN_6,GSTIN_7,GSTIN_8,GSTIN_9,GSTIN_10,IEC_NO,LEI,ADDRESS_TYPE_1,ADDRESS_TYPE_2,ADDRESS_TYPE_3,ADDRESS_TYPE_4,ADDRESS_1,REQUESTED_BY,ADDRESS_2,ADDRESS_3,ADDRESS_4,CITY_1,CITY_2,CITY_3,CITY_4,STATE_1,STATE_2,STATE_3,STATE_4,COUNTRY_1,COUNTRY_2,COUNTRY_3,COUNTRY_4,PINCODE_1,PINCODE_2,PINCODE_3,PINCODE_4,EMAIL_TYPE_1,EMAIL_TYPE_2,EMAIL_1,EMAIL_2,PHONE_TYPE_1,PHONE_TYPE_2,PHONE_TYPE_3,PHONE_1,PHONE_2,PHONE_3,AADHAR_NO,AADHAR_LINKED_STATUS,PASSPORT_DATEOFEXPIRY,DRIVING_LICENSE_DATEOFEXPIRY,NREGA_DATEOFEXPIRY,OVD_STATUS,SHOP_ESTABLISHMENT,HOME_BRANCH_CODE,HOME_BRANCH_DESCRIPTION,FATCA_FLAG,CUSTOMER_TYPE_CODE,CUSTOMER_TYPE_NAME,CUSTOMER_STATUS,CUSTOMER_SEGMENT,CUSTOMER_CATEGORY,ENTITY_TYPE,APPLICANT_TYPE,PEP,GROUPID,KYC_STATUS,DATE_OF_KYCDONE,REKYC_DUEON,RISK_CATEGORY,STAFF_EMPLOYEEID,STAFF_FLAG,YESFIRSTFLG,MINOR_FLAG,NATIONALITY,CONSTITUTION_TYPE,AADHAR_DETAILS,KYC_MODE,EXTRA_NAME1,EXTRA_NAME2,EXTRA_DATE1,EXTRA_DATE2,EXTRA_EQUALITY1,EXTRA_EQUALITY2,EXTRA_EQUALITY3,EXTRA_EQUALITY4,EXTRA_EQUALITY5,EXTRA_EQUALITY6,EXTRA_EQUALITY7,EXTRA_EQUALITY8,EXTRA_EQUALITY9,EXTRA_EQUALITY10,ORIGINATING_PRODUCT,ORIGINATING_CHANNEL,ORIGINATING_STATUS,ORIGINATING_REMARKS,ORIGINATING_LAST_UPDT,ORIGINATING_REJECTED_BY)
SELECT /*+ enable_parallel_dml parallel(6) */ SOURCE_SYSTEM,SOURCE_SYSTEM_CUSTID,INSERT_TS,SOURCE_SYSTEM_DATE,BATCH_ID,CUST_IC,CREATED_FOR,BANK_UCIC,CUST_CREATE_DATE,CUST_FIRST_NAME,CUST_MIDDLE_NAME,CUST_LAST_NAME,CUST_FULL_NAME,NAM_CUST_SHRT,NAME_SALUTATION,GENDER,DOBDOI,MOTHER_NAME,FATHER_NAME,SPOUSE_NAME,EMPLOYER_NAME,PAN,PASSPORT,VOTERID,DRIVING_LICENSE_NUMBER,NREGA,TAN,TIN,UDYAM_AADHAR_NO,CKYC,DIN,CIN,GSTIN_1,GSTIN_2,GSTIN_3,GSTIN_4,GSTIN_5,GSTIN_6,GSTIN_7,GSTIN_8,GSTIN_9,GSTIN_10,IEC_NO,LEI,ADDRESS_TYPE_1,ADDRESS_TYPE_2,ADDRESS_TYPE_3,ADDRESS_TYPE_4,ADDRESS_1,REQUESTED_BY,ADDRESS_2,ADDRESS_3,ADDRESS_4,CITY_1,CITY_2,CITY_3,CITY_4,STATE_1,STATE_2,STATE_3,STATE_4,COUNTRY_1,COUNTRY_2,COUNTRY_3,COUNTRY_4,PINCODE_1,PINCODE_2,PINCODE_3,PINCODE_4,EMAIL_TYPE_1,EMAIL_TYPE_2,EMAIL_1,EMAIL_2,PHONE_TYPE_1,PHONE_TYPE_2,PHONE_TYPE_3,PHONE_1,PHONE_2,PHONE_3,AADHAR_NO,AADHAR_LINKED_STATUS,PASSPORT_DATEOFEXPIRY,DRIVING_LICENSE_DATEOFEXPIRY,NREGA_DATEOFEXPIRY,OVD_STATUS,SHOP_ESTABLISHMENT,HOME_BRANCH_CODE,HOME_BRANCH_DESCRIPTION,FATCA_FLAG,CUSTOMER_TYPE_CODE,CUSTOMER_TYPE_NAME,CUSTOMER_STATUS,CUSTOMER_SEGMENT,CUSTOMER_CATEGORY,ENTITY_TYPE,APPLICANT_TYPE,PEP,GROUPID,KYC_STATUS,DATE_OF_KYCDONE,REKYC_DUEON,RISK_CATEGORY,STAFF_EMPLOYEEID,STAFF_FLAG,YESFIRSTFLG,MINOR_FLAG,NATIONALITY,CONSTITUTION_TYPE,AADHAR_DETAILS,KYC_MODE,EXTRA_NAME1,EXTRA_NAME2,EXTRA_DATE1,EXTRA_DATE2,EXTRA_EQUALITY1,EXTRA_EQUALITY2,EXTRA_EQUALITY3,EXTRA_EQUALITY4,EXTRA_EQUALITY5,EXTRA_EQUALITY6,EXTRA_EQUALITY7,EXTRA_EQUALITY8,EXTRA_EQUALITY9,EXTRA_EQUALITY10,ORIGINATING_PRODUCT,ORIGINATING_CHANNEL,ORIGINATING_STATUS,ORIGINATING_REMARKS,ORIGINATING_LAST_UPDT,ORIGINATING_REJECTED_BY FROM PROD_PSX_DEDUPE_STAGING.YBL_CUSTOMER_DATA_INCREMENTAL where BATCH_ID = client_batch_id;
Commit;
  -- Truncating YBL_CUSTOMER_DATA_INCREMENTAL table
DELETE /*+ PARALLEL(1) */ FROM PROD_PSX_DEDUPE_STAGING.YBL_CUSTOMER_DATA_INCREMENTAL where BATCH_ID = client_batch_id;

COMMIT;

    -- Setting status as 'C' for success
    o_status := 'C';
    
EXCEPTION
    WHEN OTHERS THEN
        -- If any error occurs, set status as 'E' for error
        o_status := 'E';
        p_descripition := 'Error in the PSX_CLIP_SUCCESS_POST_DMLS PROCEDURE';
        p_sqlerror := 'Error: ' || SQLERRM || ' at ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;
        --RAISE_APPLICATION_ERROR(-20001, 'Error occurred in the PSX_CLIP_SUCCESS_POST_DMLS procedure: ' || SQLERRM || ' at ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
END PSX_CLIP_SUCCESS_POST_DMLS;

=======================================================================================================================================

7. PSX_INDEX_REBUILDING

create or replace PROCEDURE PSX_INDEX_REBUILDING (v_status OUT VARCHAR2) AS
BEGIN

  -- DBMS_STATS.GATHER_TABLE_STATS('PSX_DEDUPE_STAGING', 'PSX_EOD_CONTROL_T', degree => 5);
  -- DBMS_STATS.GATHER_TABLE_STATS('PSX_DEDUPE_STAGING', 'YBL_CUSTOMER_DATA_INCREMENTAL', degree => 5);
   DBMS_STATS.GATHER_TABLE_STATS(USER, 'SOURCE_SYSTEM_MASTER', degree => 5, cascade=> true);
   DBMS_STATS.GATHER_TABLE_STATS(USER, 'PSX_CUSTOMER_DATA_INCREMENTAL', degree => 5, cascade=> true);
   DBMS_STATS.GATHER_TABLE_STATS(USER, 'MASTER_PSX_CUS_BLK_STG', degree => 5,cascade=> true);
   DBMS_STATS.GATHER_TABLE_STATS(USER, 'P0_PSX_CUS_BLK_TRG', degree => 5,cascade=> true);
   DBMS_STATS.GATHER_TABLE_STATS(USER, 'PSX_CLUSTER_CROSS_REF_T', degree => 5,cascade=> true);
   DBMS_STATS.GATHER_TABLE_STATS(USER, 'P0_PSX_CUS_BLK_STG', degree => 5, cascade=> true);
   DBMS_STATS.GATHER_TABLE_STATS(USER, 'PSX_CUSTUNQID_VS_PARTITIONNO', degree => 5, cascade=> true);
   DBMS_STATS.GATHER_TABLE_STATS(USER, 'PSX_CVP_STAGING', degree => 5, cascade=> true);
   DBMS_STATS.GATHER_TABLE_STATS(USER, 'PSX_RVC', degree => 5, cascade=> true);
   DBMS_STATS.GATHER_TABLE_STATS(USER, 'PSX_APP_CONFIG', degree => 5, cascade=> true);
  DBMS_STATS.GATHER_TABLE_STATS(USER, 'psx_grp_temp_t', degree => 5, cascade=> true);
  DBMS_STATS.GATHER_TABLE_STATS(USER, 'psx_cluster_audit_t', degree => 5, cascade=> true);

   
  -- DBMS_STATS.GATHER_TABLE_STATS(USER, 'CLIPDEDUPE.PSXIDS_DT_2_HASHING', degree => 5);

   v_status := 'C';  -- Success

EXCEPTION
   WHEN OTHERS THEN
      v_status := 'E';  -- Error occurred
      RAISE_APPLICATION_ERROR(-20001, 'Error occurred in the PSX_INDEX_REBUILDING procedure: ' || SQLERRM);
END PSX_INDEX_REBUILDING;

======================================================================================================================================================

8. PSX_FETCH_EOD_CONTROL_T

create or replace PROCEDURE PSX_FETCH_EOD_CONTROL_T (
    v_batch_id IN VARCHAR2,  
    v_psx_batch_id IN VARCHAR2,
    cur_output OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN cur_output FOR
    SELECT /*+ enable_parallel_dml parallel(6) */  BATCH_ID, PSX_BATCH_ID, SOURCE_SYSTEM, BATCH_TOTAL_REC_COUNT, EOD_STATUS, PSX_COUNT, ERROR_DESCRIPTION
    FROM PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T 
      WHERE PSX_BATCH_ID = v_psx_batch_id 
      AND DATA_CATEGORY = 'CUSTOMER';

EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20001, 'Error occurred in the PSX_FETCH_EOD_CONTROL_T procedure: ' || SQLERRM || ' at ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
END PSX_FETCH_EOD_CONTROL_T;

=========================================================================================================================================================
9. PSX_CLIP_FAILURE_POST_DMLS

create or replace PROCEDURE PSX_CLIP_FAILURE_POST_DMLS (
    v_psx_batch_id IN VARCHAR2,  -- Input parameter for psx_batch_id
    vBatchId IN VARCHAR2,     -- Input parameter for batch_id
    oStatus OUT VARCHAR2,          -- Output parameter for status
    p_descripition out varchar2, -- descripition
    p_sqlerror out varchar2 -- sql error
)
AS

    control_t_success_count NUMBER;
    control_t_failure_count NUMBER;
    psx_incr_count NUMBER;
    psx_stg_count NUMBER;
    psx_p0_trg_count NUMBER;
    psx_crt_count NUMBER;
    client_batch_id NUMBER;
    psx_p0_trg_total_count NUMBER;
    psx_crt_total_count NUMBER;
    total_obj_count NUMBER;


BEGIN

    -- Getting the BATCH_ID from PSX_EOD_CONTROL_T
    SELECT DISTINCT BATCH_ID 
    INTO client_batch_id 
    FROM PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T 
    WHERE PSX_BATCH_ID = v_psx_batch_id;

    -- Getting the EOD_STATUS "U" count from PSX_EOD_CONTROL_T based on PSX_BATCH_ID
    SELECT SUM(BATCH_TOTAL_REC_COUNT)
    INTO control_t_success_count
    FROM PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T
    WHERE EOD_STATUS='U' AND PSX_BATCH_ID = v_psx_batch_id;


    -- Getting the EOD_STATUS "E" count from PSX_EOD_CONTROL_T based on PSX_BATCH_ID
    SELECT SUM(BATCH_TOTAL_REC_COUNT)
    INTO control_t_failure_count
    FROM PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T
    WHERE EOD_STATUS='E' AND PSX_BATCH_ID = v_psx_batch_id;

    -- Updating the PSX_EOD_CONTROL_T table to set EOD_STATUS to 'E' where PSX_BATCH_ID = v_psx_batch_id
    UPDATE /*+ PARALLEL(1) */ PROD_PSX_DEDUPE_STAGING.PSX_EOD_CONTROL_T
    SET EOD_STATUS = 'E'
    WHERE PSX_BATCH_ID = v_psx_batch_id;

    COMMIT;


    -- Getting the count from PSX_CUSTOMER_DATA_INCREMENTAL based on PSX_BATCH_ID
    SELECT COUNT(*)
    INTO psx_incr_count 
    FROM PSX_CUSTOMER_DATA_INCREMENTAL
    WHERE PSX_BATCH_ID = v_psx_batch_id;


    -- Getting the count from MASTER_PSX_CUS_BLK_STG based on PSX_BATCH_ID
    SELECT COUNT(*)
    INTO psx_stg_count 
    FROM MASTER_PSX_CUS_BLK_STG
    WHERE PSX_BATCH_ID = v_psx_batch_id;


    -- Getting the count from P0_PSX_CUS_BLK_TRG based on PSX_BATCH_ID
    SELECT COUNT(*)
    INTO psx_p0_trg_count 
    FROM P0_PSX_CUS_BLK_TRG
    WHERE PSX_BATCH_ID = v_psx_batch_id;


    -- Getting the count from PSX_CLUSTER_CROSS_REF_T based on PSX_BATCH_ID
    SELECT COUNT(*)
    INTO psx_crt_count 
    FROM PSX_CLUSTER_CROSS_REF_T
    WHERE PSX_BATCH_ID = v_psx_batch_id;

    -- Getting the total records count from P0_PSX_CUS_BLK_TRG
    SELECT COUNT(*)
    INTO psx_p0_trg_total_count 
    FROM P0_PSX_CUS_BLK_TRG;

    -- Getting the total records count from PSX_CLUSTER_CROSS_REF_T
    SELECT COUNT(*)
    INTO psx_crt_total_count 
    FROM PSX_CLUSTER_CROSS_REF_T;

    -- Getting the total object count from PSX_OBJECT_STATS based on PSX_BATCH_ID
    SELECT CUSTOMER_P0
    INTO total_obj_count 
    FROM PSX_OBJECT_STATS
    WHERE PSX_BATCH_ID = v_psx_batch_id;

      -- Inserting all the counts in PSX_CLIP_EOD_DATA_COUNTS
    INSERT INTO PSX_CLIP_EOD_DATA_COUNTS(BATCH_ID,PSX_BATCH_ID,YBL_VALID_COUNT,YBL_INVALID_COUNT,PSX_INCR_COUNT,PSX_STG_COUNT,
    P0_TRG_COUNT,CRT_COUNT,OBJECT_TOTAL_COUNT,P0_TRG_TOTAL_COUNT,CRT_TOTAL_COUNT) VALUES(client_batch_id,v_psx_batch_id,control_t_success_count,control_t_failure_count,psx_incr_count,psx_stg_count,psx_p0_trg_count,
    psx_crt_count,total_obj_count,psx_p0_trg_total_count,psx_crt_total_count);

    COMMIT;


    -- If the update is successful, setting the output status to 'C' for success
    oStatus := 'C';

EXCEPTION
    -- In case of an error, setting the output status to 'E' for failure
    WHEN OTHERS THEN
        oStatus := 'E';
        p_descripition := 'Error in the PSX_CLIP_FAILURE_POST_DMLS PROCEDURE';
        p_sqlerror := 'Error: ' || SQLERRM || ' at ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;
        --RAISE_APPLICATION_ERROR(-20001, 'Error occurred in the PSX_CLIP_FAILURE_POST_DMLS procedure: ' || SQLERRM || ' at ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
END PSX_CLIP_FAILURE_POST_DMLS;