create or replace PROCEDURE PSX_COLLAT_DATA_VALIDATE_IMPORT_PROC 
(V_psx_batch_id IN varchar2,
  v_status OUT varchar2,
 v_desc OUT varchar2,
 v_sql_err OUT varchar2
)
 AS
 v_batch_id varchar(50);
 actual_count NUMBER;
 eod_u_status_count NUMBER;
 count_missmatch exception;
 no_eod_status_u exception;
 
 
 BEGIN
 
          BEGIN
            SELECT distinct(batch_id) INTO v_batch_id FROM YESBANK_DEV.PSX_COLLATERAL_EOD_CONTROL_T 
            WHERE EOD_STATUS='P' AND SLNO=(SELECT MIN(slno) from YESBANK_DEV.PSX_COLLATERAL_EOD_CONTROL_T where EOD_STATUS='P');
          EXCEPTION 
             WHEN OTHERS THEN
             V_status:='E';
             v_desc:='Batch ID not found to initiate EOD';
             RETURN;
          END;

            UPDATE YESBANK_DEV.PSX_COLLATERAL_EOD_CONTROL_T set psx_batch_id=v_psx_batch_id where batch_id=v_batch_id and EOD_STATUS='P';
            COMMIT;
            INSERT /*+ APPEND */  INTO psx_collateral_eod_status ( psx_batch_id, description,STATUS,MODULE,INSERT_TIME) 
            VALUES (V_PSX_BATCH_ID,'Batch_Id is fetched successfully from Control Table','C','COLLAT_VALID_IMPORT_PROC',CURRENT_TIMESTAMP);
            COMMIT;
    
   -- Validating the SOURCE_SYSTEM against SOURCE_SYSTEM_MASTER
    UPDATE /*+ PARALLEL (4) */ YESBANK_DEV.PSX_COLLATERAL_EOD_CONTROL_T t SET t.EOD_STATUS = 'E',t.ERROR_DESCRIPTION = 'Invalid Source System Name'
    WHERE t.BATCH_ID = v_batch_id AND EOD_STATUS='P'
    AND (t.SOURCE_SYSTEM IS NULL OR
     NOT EXISTS (
        SELECT /*+ PARALLEL (4)*/  1 
        FROM YESBNK_PRIME.SOURCE_SYSTEM_MASTER m
        WHERE t.SOURCE_SYSTEM = m.SOURCE_SYSTEM_NAME
     ));
    COMMIT;

  --Validating source_system in YBL_COLLATERAL_DATA_INCREMENTAL table and inserting error records in YBL_COLLATERAL_DATA_INCREMENTAL_ERROR
   INSERT /*+ APPEND */ INTO YESBANK_DEV.YBL_COLLATERAL_DATA_INCREMENTAL_ERROR
    (ACCOUNT_CLOSING_DATE,ACCOUNT_NAME,ACCOUNT_NUMBER,ACCOUNT_OPENING_DATE,ACCOUNT_STATUS,APPLICATIONID,ASSET_MAKE,ASSET_MODEL,BATCH_ID,BUILDER_ID,BUILDER_NAME,CHASSIS_NUMBER,COLLETRAL_TYPE,ENGINE_NUMBER,ENTITY_TYPE,EXTRA_EQ_COLUMN1,EXTRA_EQ_COLUMN2,EXTRA_EQ_COLUMN3,EXTRA_EQ_COLUMN4,EXTRA_EQ_COLUMN5,EXTRA_EQ_COLUMN6,FILLER1,FILLER2,FILLER3,BANK_UCIC,BRANCH_CODE,BRANCH_NAME,FILLER7,FILLER8,FILLER9,INSERT_TS,MANUFACTURING_YEAR,PRODUCT_CODE,PRODUCT_NAME,PRODUCT_TYPE,PROJECT_ID,PROJECT_NAME,PROPERTY_ADDRESS,PROPERTY_CITY,PROPERTY_DESC,PROPERTY_ID,PROPERTY_PINCODE,PROPERTY_STATE,REFERENCE_ID,REFERENCE_MOBILE_NUMBER_1,REFERENCE_MOBILE_NUMBER_2,REFERENCE_NAME,SOURCE_SYSTEM_CUST_ID,SOURCE_SYSTEM_DATE,SOURCE_SYSTEM_NAME,VEHICLE_REGISTRATION_NO)
    SELECT  /*+ PARALLEL (4)*/ 
    ACCOUNT_CLOSING_DATE,ACCOUNT_NAME,ACCOUNT_NUMBER,ACCOUNT_OPENING_DATE,ACCOUNT_STATUS,APPLICATIONID,ASSET_MAKE,ASSET_MODEL,BATCH_ID,BUILDER_ID,BUILDER_NAME,CHASSIS_NUMBER,COLLETRAL_TYPE,ENGINE_NUMBER,ENTITY_TYPE,EXTRA_EQ_COLUMN1,EXTRA_EQ_COLUMN2,EXTRA_EQ_COLUMN3,EXTRA_EQ_COLUMN4,EXTRA_EQ_COLUMN5,EXTRA_EQ_COLUMN6,FILLER1,FILLER2,FILLER3,BANK_UCIC,BRANCH_CODE,BRANCH_NAME,FILLER7,FILLER8,FILLER9,INSERT_TS,MANUFACTURING_YEAR,PRODUCT_CODE,PRODUCT_NAME,PRODUCT_TYPE,PROJECT_ID,PROJECT_NAME,PROPERTY_ADDRESS,PROPERTY_CITY,PROPERTY_DESC,PROPERTY_ID,PROPERTY_PINCODE,PROPERTY_STATE,REFERENCE_ID,REFERENCE_MOBILE_NUMBER_1,REFERENCE_MOBILE_NUMBER_2,REFERENCE_NAME,SOURCE_SYSTEM_CUST_ID,SOURCE_SYSTEM_DATE,SOURCE_SYSTEM_NAME,VEHICLE_REGISTRATION_NO
    FROM YESBANK_DEV.YBL_COLLATERAL_DATA_INCREMENTAL YBL 
    WHERE YBL.BATCH_ID=v_batch_id
    AND (YBL.SOURCE_SYSTEM_NAME IS NULL OR
    NOT EXISTS (
           SELECT /*+ PARALLEL (4)*/  1 
           FROM YESBNK_PRIME.SOURCE_SYSTEM_MASTER SSM 
           WHERE ssm.source_system_name = YBL.SOURCE_SYSTEM_NAME));
     COMMIT;
    DELETE /*+ PARALLEL (4) */ FROM YESBANK_DEV.YBL_COLLATERAL_DATA_INCREMENTAL YBL  
    WHERE YBL.BATCH_ID=v_batch_id
    AND (YBL.SOURCE_SYSTEM_NAME IS NULL OR
    NOT EXISTS (
           SELECT /*+ PARALLEL (4)*/  1 
           FROM YESBNK_PRIME.SOURCE_SYSTEM_MASTER SSM 
           WHERE ssm.source_system_name = YBL.SOURCE_SYSTEM_NAME));
    COMMIT;

    -- Comparing individual SOURCE_SYSTEM data counts for the specific v_batch_id
    FOR rec IN (
        SELECT /*+ PARALLEL (4) */ SOURCE_SYSTEM, BATCH_TOTAL_REC_COUNT
        FROM YESBANK_DEV.PSX_COLLATERAL_EOD_CONTROL_T
        WHERE BATCH_ID = v_batch_id AND EOD_STATUS='P'
    )
    LOOP
        -- Getting the actual count from YBL_COLLATERAL_DATA_INCREMENTAL for the same SOURCE_SYSTEM and v_batch_id
        SELECT /*+ PARALLEL (4) */ COUNT(*)
        INTO actual_count
        FROM YESBANK_DEV.YBL_COLLATERAL_DATA_INCREMENTAL t6
        WHERE BATCH_ID = v_batch_id
        AND SOURCE_SYSTEM_NAME = rec.SOURCE_SYSTEM;

        -- Checking if BATCH_TOTAL_REC_COUNT matches the actual count
        IF rec.BATCH_TOTAL_REC_COUNT != actual_count THEN
            -- If counts mismatch, update the EOD_STATUS to 'E' and add an error message
            UPDATE /*+ PARALLEL (4) */ YESBANK_DEV.PSX_COLLATERAL_EOD_CONTROL_T
            SET EOD_STATUS = 'E',
                ERROR_DESCRIPTION = rec.SOURCE_SYSTEM || ' data counts are mismatched'
            WHERE BATCH_ID = v_batch_id
            AND SOURCE_SYSTEM = rec.SOURCE_SYSTEM
            AND EOD_STATUS='P';
            COMMIT;
            
        ELSE
            -- If counts match, update the EOD_STATUS to 'U'
            UPDATE /*+ PARALLEL (4) */ YESBANK_DEV.PSX_COLLATERAL_EOD_CONTROL_T
            SET EOD_STATUS = 'U'
            WHERE BATCH_ID = v_batch_id
            AND SOURCE_SYSTEM = rec.SOURCE_SYSTEM
            AND EOD_STATUS='P';
            COMMIT;
        END IF;

    END LOOP;
    
           
    SELECT count(1) into eod_u_status_count FROM YESBANK_DEV.PSX_COLLATERAL_EOD_CONTROL_T where EOD_STATUS = 'U' and batch_id=v_batch_id;
    
    IF eod_u_status_count=0 THEN
      RAISE no_eod_status_u;
    END IF;
    
    INSERT /*+ APPEND */  INTO psx_collateral_eod_status (psx_batch_id, description,STATUS,MODULE,INSERT_TIME) 
    VALUES (V_PSX_BATCH_ID,'Validations Successful, Ready to import into PSX table','C','COLLAT_VALID_IMPORT_PROC',CURRENT_TIMESTAMP);
    COMMIT;
    
    --Import Data to PSX table
    INSERT INTO PSX_COLLATERAL_DATA_INCREMENTAL   (SOURCE_SYSTEM_NAME,SOURCE_SYSTEM_CUST_ID,SOURCE_SYSTEM_DATE,COLLETRAL_TYPE,ACCOUNT_NUMBER,ACCOUNT_NAME,ACCOUNT_STATUS,ACCOUNT_OPENING_DATE,ACCOUNT_CLOSING_DATE,PRODUCT_TYPE,PRODUCT_NAME,PRODUCT_CODE,APPLICATIONID,ENTITY_TYPE,ASSET_MAKE,ASSET_MODEL,VEHICLE_REGISTRATION_NO,CHASSIS_NUMBER,ENGINE_NUMBER,MANUFACTURING_YEAR,PROPERTY_ID,PROJECT_ID,PROJECT_NAME,BUILDER_ID,BUILDER_NAME,PROPERTY_ADDRESS,PROPERTY_CITY,PROPERTY_PINCODE,PROPERTY_DESC,REFERENCE_ID,REFERENCE_NAME,REFERENCE_MOBILE_NUMBER_1,REFERENCE_MOBILE_NUMBER_2,FILLER1,FILLER2,FILLER3,FILLER4,FILLER5,FILLER6,FILLER7,FILLER8,FILLER9,BATCH_ID,INSERT_TS,PSX_BATCH_ID, EXTRA_EQ_COLUMN1, EXTRA_EQ_COLUMN2, EXTRA_EQ_COLUMN3, EXTRA_EQ_COLUMN4,EXTRA_EQ_COLUMN5, EXTRA_EQ_COLUMN6,PROPERTY_STATE)
    SELECT YBL.SOURCE_SYSTEM_NAME,YBL.SOURCE_SYSTEM_CUST_ID,YBL.SOURCE_SYSTEM_DATE,YBL.COLLETRAL_TYPE,UPPER(YBL.ACCOUNT_NUMBER),YBL.ACCOUNT_NAME,YBL.ACCOUNT_STATUS,YBL.ACCOUNT_OPENING_DATE,YBL.ACCOUNT_CLOSING_DATE,YBL.PRODUCT_TYPE,YBL.PRODUCT_NAME,YBL.PRODUCT_CODE,YBL.APPLICATIONID,YBL.ENTITY_TYPE,YBL.ASSET_MAKE,YBL.ASSET_MODEL,YBL.VEHICLE_REGISTRATION_NO,YBL.CHASSIS_NUMBER,YBL.ENGINE_NUMBER,YBL.MANUFACTURING_YEAR,YBL.PROPERTY_ID,YBL.PROJECT_ID,YBL.PROJECT_NAME,YBL.BUILDER_ID,YBL.BUILDER_NAME,YBL.PROPERTY_ADDRESS,YBL.PROPERTY_CITY,YBL.PROPERTY_PINCODE,YBL.PROPERTY_DESC,YBL.REFERENCE_ID,YBL.REFERENCE_NAME,YBL.REFERENCE_MOBILE_NUMBER_1,YBL.REFERENCE_MOBILE_NUMBER_2,YBL.FILLER1,YBL.FILLER2,YBL.FILLER3,YBL.BANK_UCIC,YBL.BRANCH_CODE,YBL.BRANCH_NAME,YBL.FILLER7,YBL.FILLER8,YBL.FILLER9,YBL.BATCH_ID,YBL.INSERT_TS,v_psx_batch_id,YBL.EXTRA_EQ_COLUMN1,YBL.EXTRA_EQ_COLUMN2,YBL.EXTRA_EQ_COLUMN3,YBL.EXTRA_EQ_COLUMN4,YBL.EXTRA_EQ_COLUMN5,YBL.EXTRA_EQ_COLUMN6,YBL.PROPERTY_STATE
    FROM YESBANK_DEV.YBL_COLLATERAL_DATA_INCREMENTAL YBL  JOIN YESBANK_DEV.PSX_COLLATERAL_EOD_CONTROL_T EOD ON YBL.BATCH_ID = EOD.BATCH_ID 
    WHERE YBL.BATCH_ID = v_batch_id AND EOD.EOD_STATUS = 'U' AND YBL.SOURCE_SYSTEM_NAME = EOD.SOURCE_SYSTEM;
    COMMIT;
    
          BEGIN
    -----------------------------------------CUST_UNQ_ID BUILDING-----------------------------------------------------------
    
      -- Updating SOURCE_SYSTEM_ID in PSX_COLLATERAL_DATA_INCREMENTAL with SOURCE_SYSTEM_MASTER table
            UPDATE /*+ enable_parallel_dml parallel(6) */ PSX_COLLATERAL_DATA_INCREMENTAL CDI
            SET CDI.SOURCE_SYSTEM_ID = (SELECT SSM.SOURCE_SYSTEM_ID
                                        FROM yesbnk_prime.SOURCE_SYSTEM_MASTER SSM
                                        WHERE SSM.SOURCE_SYSTEM_NAME = CDI.SOURCE_SYSTEM_NAME);
            COMMIT;

    --Building Cust_Unq_Id based in PSX table
         UPDATE /*+ enable_parallel_dml parallel(6) */ PSX_COLLATERAL_DATA_INCREMENTAL
            SET CUST_UNQ_ID = CASE 
                                WHEN UPPER(COLLETRAL_TYPE) = 'VEHICLE' THEN SOURCE_SYSTEM_ID || '_' || ACCOUNT_NUMBER
                                WHEN UPPER(COLLETRAL_TYPE) = 'PROPERTY' THEN SOURCE_SYSTEM_ID ||'_'|| ACCOUNT_NUMBER || '_' || PROPERTY_ID
                                WHEN UPPER(COLLETRAL_TYPE) = 'REFERENCE' THEN SOURCE_SYSTEM_ID || '_' || ACCOUNT_NUMBER || '_' || REFERENCE_ID
                              END
            WHERE UPPER(COLLETRAL_TYPE) IN ('VEHICLE', 'PROPERTY', 'REFERENCE');
         COMMIT;
        EXCEPTION 
            WHEN OTHERS THEN
            V_STATUS:='E';
            V_DESC:='Error while building cust_unq_id in PSX_COLLATERAL_DATA_INCREMENTAL table';
            v_sql_err:='Error: ' || SQLERRM || ' at ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;
        END;
         INSERT /*+ APPEND */  INTO psx_collateral_eod_status (psx_batch_id, description,STATUS,MODULE,INSERT_TIME) 
         VALUES (V_PSX_BATCH_ID,'Cust_Unq_Id building is successful in the PSX table','C','COLLAT_VALID_IMPORT_PROC',CURRENT_TIMESTAMP);
        COMMIT;
        BEGIN
        ---------------------------Duplication handling based on cust_unq_id and insert_time-------------------------------------------------------
             -- v_error_location := 'Handle duplicates with same insert_ts';
        INSERT /*+ PARALLEL(6) APPEND */ INTO PSX_COLLATERAL_DATA_INCREMENTAL_ERROR (
            ERROR_DESCRIPTION,SOURCE_SYSTEM_NAME,SOURCE_SYSTEM_CUST_ID,SOURCE_SYSTEM_DATE,COLLETRAL_TYPE,ACCOUNT_NUMBER,ACCOUNT_NAME,ACCOUNT_STATUS,ACCOUNT_OPENING_DATE,ACCOUNT_CLOSING_DATE,PRODUCT_TYPE,PRODUCT_NAME,PRODUCT_CODE,APPLICATIONID,ENTITY_TYPE,ASSET_MAKE,ASSET_MODEL,VEHICLE_REGISTRATION_NO,CHASSIS_NUMBER,ENGINE_NUMBER,MANUFACTURING_YEAR,PROPERTY_ID,PROJECT_ID,PROJECT_NAME,BUILDER_ID,BUILDER_NAME,PROPERTY_ADDRESS,PROPERTY_CITY,PROPERTY_PINCODE,PROPERTY_DESC,REFERENCE_ID,REFERENCE_NAME,REFERENCE_MOBILE_NUMBER_1,REFERENCE_MOBILE_NUMBER_2,FILLER1,FILLER2,FILLER3,FILLER4,FILLER5,FILLER6,FILLER7,FILLER8,FILLER9,BATCH_ID,INSERT_TS,PSX_BATCH_ID,SOURCE_SYSTEM_ID,CUST_UNQ_ID, EXTRA_EQ_COLUMN1, EXTRA_EQ_COLUMN2, EXTRA_EQ_COLUMN3, EXTRA_EQ_COLUMN4,EXTRA_EQ_COLUMN5, EXTRA_EQ_COLUMN6,PROPERTY_STATE)
        WITH duplicates AS (
            SELECT /*+ PARALLEL(6)  */
                   SOURCE_SYSTEM_NAME,SOURCE_SYSTEM_CUST_ID,SOURCE_SYSTEM_DATE,COLLETRAL_TYPE,ACCOUNT_NUMBER,ACCOUNT_NAME,ACCOUNT_STATUS,ACCOUNT_OPENING_DATE,ACCOUNT_CLOSING_DATE,PRODUCT_TYPE,PRODUCT_NAME,PRODUCT_CODE,APPLICATIONID,ENTITY_TYPE,ASSET_MAKE,ASSET_MODEL,VEHICLE_REGISTRATION_NO,CHASSIS_NUMBER,ENGINE_NUMBER,MANUFACTURING_YEAR,PROPERTY_ID,PROJECT_ID,PROJECT_NAME,BUILDER_ID,BUILDER_NAME,PROPERTY_ADDRESS,PROPERTY_CITY,PROPERTY_PINCODE,PROPERTY_DESC,REFERENCE_ID,REFERENCE_NAME,REFERENCE_MOBILE_NUMBER_1,REFERENCE_MOBILE_NUMBER_2,FILLER1,FILLER2,FILLER3,FILLER4,FILLER5,FILLER6,FILLER7,FILLER8,FILLER9,BATCH_ID,INSERT_TS,PSX_BATCH_ID,SOURCE_SYSTEM_ID,CUST_UNQ_ID, EXTRA_EQ_COLUMN1, EXTRA_EQ_COLUMN2, EXTRA_EQ_COLUMN3, EXTRA_EQ_COLUMN4,EXTRA_EQ_COLUMN5, EXTRA_EQ_COLUMN6 ,PROPERTY_STATE,
                   ROW_NUMBER() OVER (PARTITION BY CUST_UNQ_ID,INSERT_TS ORDER BY INSERT_TS) AS row_num
            FROM PSX_COLLATERAL_DATA_INCREMENTAL
        )
        SELECT /*+ PARALLEL(6) */ 
           'CUST_UNQ_ID duplicates with same insert_ts',SOURCE_SYSTEM_NAME,SOURCE_SYSTEM_CUST_ID,SOURCE_SYSTEM_DATE,COLLETRAL_TYPE,ACCOUNT_NUMBER,ACCOUNT_NAME,ACCOUNT_STATUS,ACCOUNT_OPENING_DATE,ACCOUNT_CLOSING_DATE,PRODUCT_TYPE,PRODUCT_NAME,PRODUCT_CODE,APPLICATIONID,ENTITY_TYPE,ASSET_MAKE,ASSET_MODEL,VEHICLE_REGISTRATION_NO,CHASSIS_NUMBER,ENGINE_NUMBER,MANUFACTURING_YEAR,PROPERTY_ID,PROJECT_ID,PROJECT_NAME,BUILDER_ID,BUILDER_NAME,PROPERTY_ADDRESS,PROPERTY_CITY,PROPERTY_PINCODE,PROPERTY_DESC,REFERENCE_ID,REFERENCE_NAME,REFERENCE_MOBILE_NUMBER_1,REFERENCE_MOBILE_NUMBER_2,FILLER1,FILLER2,FILLER3,FILLER4,FILLER5,FILLER6,FILLER7,FILLER8,FILLER9,BATCH_ID,INSERT_TS,PSX_BATCH_ID,SOURCE_SYSTEM_ID,CUST_UNQ_ID, EXTRA_EQ_COLUMN1, EXTRA_EQ_COLUMN2, EXTRA_EQ_COLUMN3, EXTRA_EQ_COLUMN4,EXTRA_EQ_COLUMN5, EXTRA_EQ_COLUMN6,PROPERTY_STATE
        FROM duplicates
        WHERE row_num > 1;
        COMMIT; -- Commit to allow delete on PSX_ENPA_DATA_TEMP

        DELETE /*+ PARALLEL(6) */ FROM PSX_COLLATERAL_DATA_INCREMENTAL
        WHERE ROWID IN (
            SELECT rid
            FROM (
                SELECT /*+ PARALLEL(6) ) */
                       ROWID AS rid,
                       ROW_NUMBER() OVER (PARTITION BY CUST_UNQ_ID,INSERT_TS ORDER BY INSERT_TS) AS row_num
                FROM PSX_COLLATERAL_DATA_INCREMENTAL
            ) WHERE row_num > 1
        );
        COMMIT; -- Commit to allow next duplicate handling

        --v_error_location := 'Handle duplicates with different insert_ts';
         INSERT /*+ PARALLEL(6) APPEND */ INTO PSX_COLLATERAL_DATA_INCREMENTAL_ERROR (
            ERROR_DESCRIPTION,SOURCE_SYSTEM_NAME,SOURCE_SYSTEM_CUST_ID,SOURCE_SYSTEM_DATE,COLLETRAL_TYPE,ACCOUNT_NUMBER,ACCOUNT_NAME,ACCOUNT_STATUS,ACCOUNT_OPENING_DATE,ACCOUNT_CLOSING_DATE,PRODUCT_TYPE,PRODUCT_NAME,PRODUCT_CODE,APPLICATIONID,ENTITY_TYPE,ASSET_MAKE,ASSET_MODEL,VEHICLE_REGISTRATION_NO,CHASSIS_NUMBER,ENGINE_NUMBER,MANUFACTURING_YEAR,PROPERTY_ID,PROJECT_ID,PROJECT_NAME,BUILDER_ID,BUILDER_NAME,PROPERTY_ADDRESS,PROPERTY_CITY,PROPERTY_PINCODE,PROPERTY_DESC,REFERENCE_ID,REFERENCE_NAME,REFERENCE_MOBILE_NUMBER_1,REFERENCE_MOBILE_NUMBER_2,FILLER1,FILLER2,FILLER3,FILLER4,FILLER5,FILLER6,FILLER7,FILLER8,FILLER9,BATCH_ID,INSERT_TS,PSX_BATCH_ID,SOURCE_SYSTEM_ID,CUST_UNQ_ID, EXTRA_EQ_COLUMN1, EXTRA_EQ_COLUMN2, EXTRA_EQ_COLUMN3, EXTRA_EQ_COLUMN4,EXTRA_EQ_COLUMN5, EXTRA_EQ_COLUMN6,PROPERTY_STATE )
        WITH duplicates AS (
            SELECT /*+ PARALLEL(6)  */
                   SOURCE_SYSTEM_NAME,SOURCE_SYSTEM_CUST_ID,SOURCE_SYSTEM_DATE,COLLETRAL_TYPE,ACCOUNT_NUMBER,ACCOUNT_NAME,ACCOUNT_STATUS,ACCOUNT_OPENING_DATE,ACCOUNT_CLOSING_DATE,PRODUCT_TYPE,PRODUCT_NAME,PRODUCT_CODE,APPLICATIONID,ENTITY_TYPE,ASSET_MAKE,ASSET_MODEL,VEHICLE_REGISTRATION_NO,CHASSIS_NUMBER,ENGINE_NUMBER,MANUFACTURING_YEAR,PROPERTY_ID,PROJECT_ID,PROJECT_NAME,BUILDER_ID,BUILDER_NAME,PROPERTY_ADDRESS,PROPERTY_CITY,PROPERTY_PINCODE,PROPERTY_DESC,REFERENCE_ID,REFERENCE_NAME,REFERENCE_MOBILE_NUMBER_1,REFERENCE_MOBILE_NUMBER_2,FILLER1,FILLER2,FILLER3,FILLER4,FILLER5,FILLER6,FILLER7,FILLER8,FILLER9,BATCH_ID,INSERT_TS,PSX_BATCH_ID,SOURCE_SYSTEM_ID,CUST_UNQ_ID, EXTRA_EQ_COLUMN1, EXTRA_EQ_COLUMN2, EXTRA_EQ_COLUMN3, EXTRA_EQ_COLUMN4,EXTRA_EQ_COLUMN5, EXTRA_EQ_COLUMN6,PROPERTY_STATE,
                   ROW_NUMBER() OVER (PARTITION BY CUST_UNQ_ID ORDER BY INSERT_TS DESC) AS row_num
            FROM PSX_COLLATERAL_DATA_INCREMENTAL
        )
        SELECT /*+ PARALLEL(6) */ 
           'CUST_UNQ_ID duplicates with different insert_ts',SOURCE_SYSTEM_NAME,SOURCE_SYSTEM_CUST_ID,SOURCE_SYSTEM_DATE,COLLETRAL_TYPE,ACCOUNT_NUMBER,ACCOUNT_NAME,ACCOUNT_STATUS,ACCOUNT_OPENING_DATE,ACCOUNT_CLOSING_DATE,PRODUCT_TYPE,PRODUCT_NAME,PRODUCT_CODE,APPLICATIONID,ENTITY_TYPE,ASSET_MAKE,ASSET_MODEL,VEHICLE_REGISTRATION_NO,CHASSIS_NUMBER,ENGINE_NUMBER,MANUFACTURING_YEAR,PROPERTY_ID,PROJECT_ID,PROJECT_NAME,BUILDER_ID,BUILDER_NAME,PROPERTY_ADDRESS,PROPERTY_CITY,PROPERTY_PINCODE,PROPERTY_DESC,REFERENCE_ID,REFERENCE_NAME,REFERENCE_MOBILE_NUMBER_1,REFERENCE_MOBILE_NUMBER_2,FILLER1,FILLER2,FILLER3,FILLER4,FILLER5,FILLER6,FILLER7,FILLER8,FILLER9,BATCH_ID,INSERT_TS,PSX_BATCH_ID,SOURCE_SYSTEM_ID,CUST_UNQ_ID, EXTRA_EQ_COLUMN1, EXTRA_EQ_COLUMN2, EXTRA_EQ_COLUMN3, EXTRA_EQ_COLUMN4,EXTRA_EQ_COLUMN5, EXTRA_EQ_COLUMN6,PROPERTY_STATE
        FROM duplicates
        WHERE row_num > 1;
        COMMIT;

        DELETE /*+ PARALLEL(6) */ FROM PSX_COLLATERAL_DATA_INCREMENTAL
        WHERE ROWID IN (
            SELECT rid
            FROM (
                SELECT /*+ PARALLEL(6) ) */
                       ROWID AS rid,
                       ROW_NUMBER() OVER (PARTITION BY CUST_UNQ_ID ORDER BY INSERT_TS DESC) AS row_num
                FROM PSX_COLLATERAL_DATA_INCREMENTAL
            ) WHERE row_num > 1
        );
        COMMIT;
         EXCEPTION 
            WHEN OTHERS THEN
            V_STATUS:='E';
            V_DESC:='Error while handling cust_unq_id duplication';
            v_sql_err:='Error: ' || SQLERRM || ' at ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;
        END;
          INSERT /*+ APPEND */  INTO psx_collateral_eod_status (psx_batch_id, description,STATUS,MODULE,INSERT_TIME) 
         VALUES (V_PSX_BATCH_ID,'Duplication handling is successful','C','COLLAT_VALID_IMPORT_PROC',CURRENT_TIMESTAMP);
        COMMIT;
        
    
    --Send success status
    V_status:='C';
    v_desc:='PSX_COLLAT_DATA_VALIDATE_IMPORT_PROC is success';

    EXCEPTION
        
     WHEN no_eod_status_u THEN
       V_status:='E';
       V_desc:='Validations failed, No Proper data to continue EOD';
       RETURN;
     WHEN count_missmatch THEN
       V_status:='E';
       V_desc:='Count Missmatch between control table and incremental table';
       RETURN;
     WHEN OTHERS THEN 
      V_status:='E';
      V_desc:='Error in the PSX_COLLAT_DATA_VALIDATE_IMPORT_PROC procedure';
      v_sql_err:='Error: ' || SQLERRM || ' at ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;
       RETURN;

 END PSX_COLLAT_DATA_VALIDATE_IMPORT_PROC;
 ===========================================================================================================================
 create or replace PROCEDURE PSX_COLLATERAL_EOD_STG_PROC
(V_PSX_BATCH_ID IN varchar,
v_status OUT varchar2,
v_desc OUT varchar2,
v_sql_err OUT varchar2)
AS
v_batch_id varchar(50);
V_INCR_COUNT NUMBER;

BEGIN
    INSERT /*+ APPEND */  INTO psx_collateral_eod_status (psx_batch_id, description,STATUS,MODULE,INSERT_TIME) 
    VALUES (V_PSX_BATCH_ID,'Collateral eod Stg(Incremental) Data processing started','C','COLLATERAL_EOD_PROC',CURRENT_TIMESTAMP);
    COMMIT;
      BEGIN 
            insert /*+ APPEND */ into master_psx_col_blk_stg_hist
                (CUST_UNQ_ID,SOURCE_SYSTEM_NAME,SOURCE_SYSTEM_CUST_ID,BATCH_ID,CLIENT_REQUESTID,FEED_SYS_ID,REQUEST_TYPE,REQUESTED_BY,UNIQUEID,PSX_BATCH_ID,OLD_PSX_BATCH_ID,LCHGTIME,DUIFLAG,EVENTTYPE,INSERT_TIME,PARTITION_NUMBER,NSPKEY,RECORD_ID,ICCLEANING_SPECTRUM,SOURCE_SYSTEM_DATE,COLLETRAL_TYPE,ACCOUNT_NUMBER,ACCOUNT_NAME,ACCOUNT_STATUS,ACCOUNT_OPENING_DATE,ACCOUNT_CLOSING_DATE,PRODUCT_TYPE,PRODUCT_NAME,PRODUCT_CODE,APPLICATIONID,ENTITY_TYPE,ASSET_MAKE,ASSET_MODEL,VEHICLE_REGISTRATION_NO,CHASSIS_NUMBER,ENGINE_NUMBER,MANUFACTURING_YEAR,PROPERTY_ID,PROJECT_ID,PROJECT_NAME,BUILDER_ID,BUILDER_NAME,PROPERTY_ADDRESS,ADDRESS_TYPE1,PROPERTY_CITY,PROPERTY_PINCODE,PINCODE_TYPE1,PROPERTY_DESC,REFERENCE_ID,POSIDEX_UCIC,PROPERTY_STATE,REFERENCE_NAME,REFERENCE_MOBILE_NUMBER_1,PHONE_TYPE1,REFERENCE_MOBILE_NUMBER_2,PHONE_TYPE2,FILLER1,FILLER2,FILLER3,FILLER4,FILLER5,FILLER6,FILLER7,FILLER8,FILLER9,EXTRA_EQ_COLUMN1,EXTRA_EQ_COLUMN2,EXTRA_EQ_COLUMN3,EXTRA_EQ_COLUMN4,EXTRA_EQ_COLUMN5,EXTRA_EQ_COLUMN6,ADJACENCYLIST,ISPARTIAL,CLUSTERING_0,CLUSTERING_CNT_0,EQUATION_0,CLUSTERING_1,CLUSTERING_CNT_1,EQUATION_1,CLUSTERING_2,CLUSTERING_CNT_2,EQUATION_2,CLUSTERING_3,CLUSTERING_CNT_3,EQUATION_3)
            select /*+ PARALLEL */ 
			     CUST_UNQ_ID,SOURCE_SYSTEM_NAME,SOURCE_SYSTEM_CUST_ID,BATCH_ID,CLIENT_REQUESTID,FEED_SYS_ID,REQUEST_TYPE,REQUESTED_BY,UNIQUEID,PSX_BATCH_ID,OLD_PSX_BATCH_ID,LCHGTIME,DUIFLAG,EVENTTYPE,INSERT_TIME,PARTITION_NUMBER,NSPKEY,RECORD_ID,ICCLEANING_SPECTRUM,SOURCE_SYSTEM_DATE,COLLETRAL_TYPE,ACCOUNT_NUMBER,ACCOUNT_NAME,ACCOUNT_STATUS,ACCOUNT_OPENING_DATE,ACCOUNT_CLOSING_DATE,PRODUCT_TYPE,PRODUCT_NAME,PRODUCT_CODE,APPLICATIONID,ENTITY_TYPE,ASSET_MAKE,ASSET_MODEL,VEHICLE_REGISTRATION_NO,CHASSIS_NUMBER,ENGINE_NUMBER,MANUFACTURING_YEAR,PROPERTY_ID,PROJECT_ID,PROJECT_NAME,BUILDER_ID,BUILDER_NAME,PROPERTY_ADDRESS,ADDRESS_TYPE1,PROPERTY_CITY,PROPERTY_PINCODE,PINCODE_TYPE1,PROPERTY_DESC,REFERENCE_ID,POSIDEX_UCIC,PROPERTY_STATE,REFERENCE_NAME,REFERENCE_MOBILE_NUMBER_1,PHONE_TYPE1,REFERENCE_MOBILE_NUMBER_2,PHONE_TYPE2,FILLER1,FILLER2,FILLER3,FILLER4,FILLER5,FILLER6,FILLER7,FILLER8,FILLER9,EXTRA_EQ_COLUMN1,EXTRA_EQ_COLUMN2,EXTRA_EQ_COLUMN3,EXTRA_EQ_COLUMN4,EXTRA_EQ_COLUMN5,EXTRA_EQ_COLUMN6,ADJACENCYLIST,ISPARTIAL,CLUSTERING_0,CLUSTERING_CNT_0,EQUATION_0,CLUSTERING_1,CLUSTERING_CNT_1,EQUATION_1,CLUSTERING_2,CLUSTERING_CNT_2,EQUATION_2,CLUSTERING_3,CLUSTERING_CNT_3,EQUATION_3
            from master_psx_col_blk_stg;
            COMMIT;
             EXECUTE IMMEDIATE 'TRUNCATE table master_psx_col_blk_stg DROP STORAGE';
       EXCEPTION
            WHEN OTHERS THEN
                V_STATUS := 'E';
                v_desc := 'Error while auditing Master STG table';
                v_sql_err := 'Error: ' || SQLERRM || ' at ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;
                RETURN;
       END;

--Moving data from PSX_COLLATERAL_DATA_INCREMENTAL to master_psx_col_blk_stg
        BEGIN
            SELECT  /*+ PARALLEL */ COUNT(1)INTO V_INCR_COUNT FROM PSX_COLLATERAL_DATA_INCREMENTAL WHERE psx_batch_id = V_PSX_BATCH_ID;
            IF V_INCR_COUNT = 0 THEN
                -- Set the OUT parameter with a success message
                v_desc := 'No Incremental Data found for Collateral eod';
                INSERT /*+ APPEND */ INTO psx_collateral_eod_status ( psx_batch_id, description,STATUS,MODULE,INSERT_TIME) 
                VALUES (V_PSX_BATCH_ID,v_desc,'C','COLLATERAL_EOD_PROC',CURRENT_TIMESTAMP);
                COMMIT;
            END IF;

            IF V_INCR_COUNT > 0 THEN
                select /*+ PARALLEL */  distinct(batch_id) into v_batch_id from PSX_Collateral_Data_Incremental where psx_batch_id=V_PSX_BATCH_ID;
                INSERT /*+ APPEND */ INTO psx_collateral_eod_status ( psx_batch_id, description,STATUS,MODULE,INSERT_TIME) 
                VALUES (V_PSX_BATCH_ID,'Incremental Data found for Collateral EOD process','C','COLLATERAL_EOD_PROC',CURRENT_TIMESTAMP);
                COMMIT;

                -- Inserting data from PSX_Collateral_Data_Incremental into master_psx_col_blk_stg
                 INSERT /*+ APPEND */ INTO master_psx_col_blk_stg(
				SOURCE_SYSTEM_NAME,SOURCE_SYSTEM_CUST_ID,SOURCE_SYSTEM_DATE,COLLETRAL_TYPE,ACCOUNT_NUMBER,ACCOUNT_NAME,ACCOUNT_STATUS,ACCOUNT_OPENING_DATE,ACCOUNT_CLOSING_DATE,PRODUCT_TYPE,PRODUCT_NAME,PRODUCT_CODE,APPLICATIONID,ENTITY_TYPE,ASSET_MAKE,ASSET_MODEL,VEHICLE_REGISTRATION_NO,CHASSIS_NUMBER,ENGINE_NUMBER,MANUFACTURING_YEAR,PROPERTY_ID,PROJECT_ID,PROJECT_NAME,BUILDER_ID,BUILDER_NAME,PROPERTY_ADDRESS,PROPERTY_CITY,PROPERTY_PINCODE,PROPERTY_DESC,REFERENCE_ID,REFERENCE_NAME,REFERENCE_MOBILE_NUMBER_1,REFERENCE_MOBILE_NUMBER_2,FILLER1,FILLER2,FILLER3,FILLER4,FILLER5,FILLER6,FILLER7,FILLER8,FILLER9,BATCH_ID,PSX_BATCH_ID,CUST_UNQ_ID, EXTRA_EQ_COLUMN1, EXTRA_EQ_COLUMN2, EXTRA_EQ_COLUMN3, EXTRA_EQ_COLUMN4,EXTRA_EQ_COLUMN5, EXTRA_EQ_COLUMN6,PROPERTY_STATE,
                    EVENTTYPE, 
                    DUIFLAG, 
                    INSERT_TIME, 
                    LCHGTIME)
                SELECT  /*+ PARALLEL */ 
                 SOURCE_SYSTEM_NAME,SOURCE_SYSTEM_CUST_ID,SOURCE_SYSTEM_DATE,COLLETRAL_TYPE,ACCOUNT_NUMBER,ACCOUNT_NAME,ACCOUNT_STATUS,ACCOUNT_OPENING_DATE,ACCOUNT_CLOSING_DATE,PRODUCT_TYPE,PRODUCT_NAME,PRODUCT_CODE,APPLICATIONID,ENTITY_TYPE,ASSET_MAKE,ASSET_MODEL,VEHICLE_REGISTRATION_NO,CHASSIS_NUMBER,ENGINE_NUMBER,MANUFACTURING_YEAR,PROPERTY_ID,PROJECT_ID,PROJECT_NAME,BUILDER_ID,BUILDER_NAME,PROPERTY_ADDRESS,PROPERTY_CITY,PROPERTY_PINCODE,PROPERTY_DESC,REFERENCE_ID,REFERENCE_NAME,REFERENCE_MOBILE_NUMBER_1,REFERENCE_MOBILE_NUMBER_2,FILLER1,FILLER2,FILLER3,FILLER4,FILLER5,FILLER6,FILLER7,FILLER8,FILLER9,BATCH_ID,PSX_BATCH_ID,CUST_UNQ_ID, EXTRA_EQ_COLUMN1, EXTRA_EQ_COLUMN2, EXTRA_EQ_COLUMN3, EXTRA_EQ_COLUMN4,EXTRA_EQ_COLUMN5, EXTRA_EQ_COLUMN6,PROPERTY_STATE,
                    'INCREMENTAL' AS EVENTTYPE, 
                    'I_OR_U' AS DUIFLAG, 
                    INSERT_TS AS INSERT_TIME,
                    CURRENT_TIMESTAMP  AS LCHGTIME
                FROM PSX_Collateral_Data_Incremental where psx_batch_id=V_PSX_BATCH_ID; 
                COMMIT;
            END IF;
        EXCEPTION
            WHEN OTHERS THEN
                V_STATUS := 'E';
                v_desc := 'Error while moving PSX_Collateral_Data_Incremental data to master_psx_col_blk_stg table';
                v_sql_err := 'Error: ' || SQLERRM || ' at ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;
                RETURN;
        END;

        V_STATUS := 'C';
        v_desc := 'Collateral eod Stg(Incremental) Data processing completed';
        INSERT /*+ APPEND */ INTO psx_collateral_eod_status (psx_batch_id, description,STATUS,MODULE,INSERT_TIME) 
        VALUES (V_PSX_BATCH_ID,v_desc,'C','COLLATERAL_EOD_PROC',CURRENT_TIMESTAMP);
        COMMIT;


   
END PSX_COLLATERAL_EOD_STG_PROC;
==============================================================================================================================================
create or replace PROCEDURE PSX_AUDIT_AND_DELETIONS_PROC 
(v_psx_batch_id IN VARCHAR2,
 retentionDay IN number,
 v_status OUT VARCHAR2,
 v_desc OUT VARCHAR2,
 v_sql_err OUT VARCHAR2)
AS
v_batch_id VARCHAR(50);
BEGIN
     INSERT /*+ APPEND */ INTO PSX_COLLATERAL_EOD_STATUS (psx_batch_id, description,STATUS,MODULE,INSERT_TIME)
     VALUES (V_PSX_BATCH_ID,'Audition and Deletion of tables procedure started','C','PSX_AUD_DEL_PROC',CURRENT_TIMESTAMP);
     COMMIT;


    --AUDITING PSX_COLLATERAL_DATA_INCREMENTAL
    INSERT /*+ APPEND */ INTO PSX_COLLATERAL_DATA_INCREMENTAL_HIST
        (SOURCE_SYSTEM_NAME,SOURCE_SYSTEM_CUST_ID,SOURCE_SYSTEM_DATE,COLLETRAL_TYPE,ACCOUNT_NUMBER,ACCOUNT_NAME,ACCOUNT_STATUS,ACCOUNT_OPENING_DATE,ACCOUNT_CLOSING_DATE,PRODUCT_TYPE,PRODUCT_NAME,PRODUCT_CODE,APPLICATIONID,ENTITY_TYPE,ASSET_MAKE,ASSET_MODEL,VEHICLE_REGISTRATION_NO,CHASSIS_NUMBER,ENGINE_NUMBER,MANUFACTURING_YEAR,PROPERTY_ID,PROJECT_ID,PROJECT_NAME,BUILDER_ID,BUILDER_NAME,PROPERTY_ADDRESS,PROPERTY_CITY,PROPERTY_PINCODE,PROPERTY_DESC,REFERENCE_ID,REFERENCE_NAME,REFERENCE_MOBILE_NUMBER_1,REFERENCE_MOBILE_NUMBER_2,FILLER1,FILLER2,FILLER3,FILLER4,FILLER5,FILLER6,FILLER7,FILLER8,FILLER9,BATCH_ID,INSERT_TS,PSX_BATCH_ID,SOURCE_SYSTEM_ID,CUST_UNQ_ID, EXTRA_EQ_COLUMN1, EXTRA_EQ_COLUMN2, EXTRA_EQ_COLUMN3, EXTRA_EQ_COLUMN4,EXTRA_EQ_COLUMN5, EXTRA_EQ_COLUMN6,PROPERTY_STATE)
    SELECT  /*+ PARALLEL (4)*/ SOURCE_SYSTEM_NAME,SOURCE_SYSTEM_CUST_ID,SOURCE_SYSTEM_DATE,COLLETRAL_TYPE,ACCOUNT_NUMBER,ACCOUNT_NAME,ACCOUNT_STATUS,ACCOUNT_OPENING_DATE,ACCOUNT_CLOSING_DATE,PRODUCT_TYPE,PRODUCT_NAME,PRODUCT_CODE,APPLICATIONID,ENTITY_TYPE,ASSET_MAKE,ASSET_MODEL,VEHICLE_REGISTRATION_NO,CHASSIS_NUMBER,ENGINE_NUMBER,MANUFACTURING_YEAR,PROPERTY_ID,PROJECT_ID,PROJECT_NAME,BUILDER_ID,BUILDER_NAME,PROPERTY_ADDRESS,PROPERTY_CITY,PROPERTY_PINCODE,PROPERTY_DESC,REFERENCE_ID,REFERENCE_NAME,REFERENCE_MOBILE_NUMBER_1,REFERENCE_MOBILE_NUMBER_2,FILLER1,FILLER2,FILLER3,FILLER4,FILLER5,FILLER6,FILLER7,FILLER8,FILLER9,BATCH_ID,INSERT_TS,PSX_BATCH_ID,SOURCE_SYSTEM_ID,CUST_UNQ_ID, EXTRA_EQ_COLUMN1, EXTRA_EQ_COLUMN2, EXTRA_EQ_COLUMN3, EXTRA_EQ_COLUMN4,EXTRA_EQ_COLUMN5, EXTRA_EQ_COLUMN6,PROPERTY_STATE 
    from PSX_COLLATERAL_DATA_INCREMENTAL WHERE psx_batch_id=v_psx_batch_id;
    COMMIT;
    --TRUNCATING PSX_COLLATERAL_DATA_INCREMENTAL
    --EXECUTE IMMEDIATE 'TRUNCATE TABLE PRIME360_CUS_STG DROP STORAGE';
    DELETE FROM PSX_COLLATERAL_DATA_INCREMENTAL WHERE psx_batch_id=v_psx_batch_id;
    COMMIT;
          SELECT BATCH_ID INTO  v_batch_id FROM YESBANK_DEV.psx_collateral_eod_control_t WHERE psx_batch_id=v_psx_batch_id  AND eod_status='C' fetch first 1 rows only;
         --move YBL_COLLATERAL_DATA_INCREMENTAL to YBL_COLLATERAL_DATA_INCREMENTAL_HIST with v_batch_id and delete the same in YBL_COLLATERAL_DATA_INCREMENTAL 
           INSERT /*+ APPEND */ INTO YESBANK_DEV.YBL_COLLATERAL_DATA_INCREMENTAL_HIST(
           SOURCE_SYSTEM_NAME,SOURCE_SYSTEM_CUST_ID,SOURCE_SYSTEM_DATE,COLLETRAL_TYPE,ACCOUNT_NUMBER,ACCOUNT_NAME,ACCOUNT_STATUS,ACCOUNT_OPENING_DATE,ACCOUNT_CLOSING_DATE,PRODUCT_TYPE,PRODUCT_NAME,PRODUCT_CODE,APPLICATIONID,ENTITY_TYPE,ASSET_MAKE,ASSET_MODEL,VEHICLE_REGISTRATION_NO,CHASSIS_NUMBER,ENGINE_NUMBER,MANUFACTURING_YEAR,PROPERTY_ID,PROJECT_ID,PROJECT_NAME,BUILDER_ID,BUILDER_NAME,PROPERTY_ADDRESS,PROPERTY_CITY,PROPERTY_PINCODE,PROPERTY_DESC,REFERENCE_ID,REFERENCE_NAME,REFERENCE_MOBILE_NUMBER_1,REFERENCE_MOBILE_NUMBER_2,FILLER1,FILLER2,FILLER3,BANK_UCIC,BRANCH_CODE,BRANCH_NAME,FILLER7,FILLER8,FILLER9,BATCH_ID,INSERT_TS, EXTRA_EQ_COLUMN1, EXTRA_EQ_COLUMN2, EXTRA_EQ_COLUMN3, EXTRA_EQ_COLUMN4,EXTRA_EQ_COLUMN5, EXTRA_EQ_COLUMN6,PROPERTY_STATE )
           SELECT /*+ PARALLEL */  SOURCE_SYSTEM_NAME,SOURCE_SYSTEM_CUST_ID,SOURCE_SYSTEM_DATE,COLLETRAL_TYPE,ACCOUNT_NUMBER,ACCOUNT_NAME,ACCOUNT_STATUS,ACCOUNT_OPENING_DATE,ACCOUNT_CLOSING_DATE,PRODUCT_TYPE,PRODUCT_NAME,PRODUCT_CODE,APPLICATIONID,ENTITY_TYPE,ASSET_MAKE,ASSET_MODEL,VEHICLE_REGISTRATION_NO,CHASSIS_NUMBER,ENGINE_NUMBER,MANUFACTURING_YEAR,PROPERTY_ID,PROJECT_ID,PROJECT_NAME,BUILDER_ID,BUILDER_NAME,PROPERTY_ADDRESS,PROPERTY_CITY,PROPERTY_PINCODE,PROPERTY_DESC,REFERENCE_ID,REFERENCE_NAME,REFERENCE_MOBILE_NUMBER_1,REFERENCE_MOBILE_NUMBER_2,FILLER1,FILLER2,FILLER3,BANK_UCIC,BRANCH_CODE,BRANCH_NAME,FILLER7,FILLER8,FILLER9,BATCH_ID,INSERT_TS, EXTRA_EQ_COLUMN1, EXTRA_EQ_COLUMN2, EXTRA_EQ_COLUMN3, EXTRA_EQ_COLUMN4,EXTRA_EQ_COLUMN5, EXTRA_EQ_COLUMN6,PROPERTY_STATE
           FROM YESBANK_DEV.YBL_COLLATERAL_DATA_INCREMENTAL where BATCH_ID=v_batch_id and source_system_name IN (
           SELECT source_system FROM YESBANK_DEV.psx_collateral_eod_control_t WHERE psx_batch_id=v_psx_batch_id  AND eod_status='C');
           COMMIT;
            --DELETE FROM YBL_COLLATERAL_DATA_INCREMENTAL where BATCH_ID=v_batch_id; 
            DELETE FROM YESBANK_DEV.YBL_COLLATERAL_DATA_INCREMENTAL where BATCH_ID=v_batch_id and source_system_name IN (
           SELECT source_system FROM YESBANK_DEV.psx_collateral_eod_control_t WHERE psx_batch_id=v_psx_batch_id  AND eod_status='C');
            COMMIT;
            
--            UPDATE YESBANK_DEV.psx_collateral_eod_control_t SET ERROR_DESCRIPTION='Collateral EOD is successful' WHERE psx_batch_id=v_psx_batch_id  AND eod_status='C';
--            COMMIT;




    BEGIN

        -- Move and delete records from PSX_REQUEST
        INSERT INTO PSX_REQUEST_HIST SELECT * FROM PSX_REQUEST WHERE INSERT_TIME < TRUNC(SYSDATE - retentionDay);
        DELETE /*+ PARALLEL (4)*/  FROM PSX_REQUEST WHERE INSERT_TIME < TRUNC(SYSDATE - retentionDay);


         -- Move and delete records from PSX_WS_AUDIT
        INSERT INTO PSX_WS_AUDIT_HIST SELECT * FROM PSX_WS_AUDIT WHERE INSERT_TIME < TRUNC(SYSDATE - retentionDay);
        DELETE /*+ PARALLEL (4)*/ FROM PSX_WS_AUDIT WHERE INSERT_TIME < TRUNC(SYSDATE - retentionDay);

        -- Move and delete records from MASTER_PSX_CUS_BLK_REQUEST
        INSERT INTO MASTER_PSX_COL_BLK_REQUEST_HIST SELECT * FROM MASTER_PSX_COL_BLK_REQUEST WHERE INSERT_TIME < TRUNC(SYSDATE - retentionDay);
        DELETE FROM MASTER_PSX_COL_BLK_REQUEST WHERE INSERT_TIME < TRUNC(SYSDATE - retentionDay);

        -- Move and delete records from PSX_REPORT_INPUT_OUTPUT
        INSERT INTO PSX_REPORT_INPUT_OUTPUT_HIST SELECT * FROM PSX_REPORT_INPUT_OUTPUT WHERE INSERT_TIME < TRUNC(SYSDATE - retentionDay);
        DELETE FROM PSX_REPORT_INPUT_OUTPUT WHERE INSERT_TIME < TRUNC(SYSDATE - retentionDay);

        -- Commit after all operations
        COMMIT;

    EXCEPTION
           WHEN OTHERS THEN
           v_status:='E';
           v_desc:='Error in deleting data from history tables';
           v_sql_err:= SQLERRM || ' at ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;
           RETURN;
    END;

INSERT /*+ APPEND */ INTO PSX_COLLATERAL_EOD_STATUS (psx_batch_id, description,STATUS,MODULE,INSERT_TIME)
VALUES (V_PSX_BATCH_ID,'Audition and Deletion of tables procedure completed','C','PSX_AUD_DEL_PROC',CURRENT_TIMESTAMP);
COMMIT;
v_status:='C';
v_desc:='AUDIT_AND_DELETIONS_PROCEDURE Execution Success' ;

EXCEPTION
       WHEN OTHERS THEN
	   v_status:='E';
	   v_desc:='Error in AUDIT_AND_DELETIONS_PROCEDURE' ;
       v_sql_err:= SQLERRM || ' at ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE;
	   RETURN;


END PSX_AUDIT_AND_DELETIONS_PROC;



--- Added One more line 
